const LANG = {
  zh: {
    title: '🌤️ 攝影天氣助手',
    desc: '選擇地區，查看未來三天最佳攝影景點推薦<br>即時能見度預報地圖・天氣感知評分・季節限定提示',
    regions: [
      {
        name: '🇹🇼 台灣',
        desc: '百岳雲海・海岸晨曦・城市夜景',
        subs: [
          { label: '📋 全部台灣景點', href: '/summary?region=tw' },
          { label: '🏔️ 台灣本島', href: '/summary?region=tw',
            onClick: 'loadSubRegion("tw","mainland")' },
          { label: '🏝️ 外島', href: '/summary?region=tw',
            onClick: 'loadSubRegion("tw","outlier")' },
        ],
      },
      {
        name: '🇯🇵 日本',
        desc: '富士山冠雪・京都紅葉・北海道夜景',
        subs: [
          { label: '📋 全部日本景點', href: '/summary?region=jp' },
          { label: '🗾 北海道', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","hokkaido")' },
          { label: '🗾 東北', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","tohoku")' },
          { label: '🗾 關東', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kanto")' },
          { label: '🗾 中部北陸', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","chubu")' },
          { label: '🗾 關西', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kansai")' },
          { label: '🗾 中國四國', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","chugoku_shikoku")' },
          { label: '🗾 九州', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kyushu")' },
        ],
      },
      {
        name: '🇺🇸 美國',
        desc: '國家公園曠野之美・城市天際線',
        subs: [
          { label: '📋 全部美國景點', href: '/summary?region=us' },
          { label: '🌄 美西', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","west")' },
          { label: '🏔️ 美中', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","central")' },
          { label: '🏙️ 美東', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","east")' },
        ],
        subs_ak: [
          { label: '🏔️ 阿拉斯加', href: '/summary?region=ak' },
        ],
      },
    ],
    footer: 'PhotoWeather © 2026 · 資料來源 Open-Meteo API',
    lastUpdate: '上次更新',
    nextUpdate: '下次更新',
    noData: '無資料',
  },
  en: {
    title: '🌤️ Photo Weather Assistant',
    desc: 'Select a region to see the best photography spots for the next 3 days<br>Visibility forecast map · Weather-aware scoring · Seasonal tips',
    regions: [
      {
        name: '🇹🇼 Taiwan',
        desc: 'Alpine cloud seas, coastal sunrises, cityscapes',
        subs: [
          { label: '📋 All Taiwan Spots', href: '/summary?region=tw' },
          { label: '🏔️ Main Island', href: '/summary?region=tw',
            onClick: 'loadSubRegion("tw","mainland")' },
          { label: '🏝️ Outer Islands', href: '/summary?region=tw',
            onClick: 'loadSubRegion("tw","outlier")' },
        ],
      },
      {
        name: '🇯🇵 Japan',
        desc: 'Mt Fuji, Kyoto autumn leaves, Hokkaido nights',
        subs: [
          { label: '📋 All Japan Spots', href: '/summary?region=jp' },
          { label: '🗾 Hokkaido', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","hokkaido")' },
          { label: '🗾 Tohoku', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","tohoku")' },
          { label: '🗾 Kanto', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kanto")' },
          { label: '🗾 Chubu', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","chubu")' },
          { label: '🗾 Kansai', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kansai")' },
          { label: '🗾 Chugoku/Shikoku', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","chugoku_shikoku")' },
          { label: '🗾 Kyushu', href: '/summary?region=jp',
            onClick: 'loadSubRegion("jp","kyushu")' },
        ],
      },
      {
        name: '🇺🇸 United States',
        desc: 'National parks, iconic skylines',
        subs: [
          { label: '📋 All US Spots', href: '/summary?region=us' },
          { label: '🌄 West', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","west")' },
          { label: '🏔️ Central', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","central")' },
          { label: '🏙️ East', href: '/summary?region=us',
            onClick: 'loadSubRegion("us","east")' },
        ],
        subs_ak: [
          { label: '🏔️ Alaska', href: '/summary?region=ak' },
        ],
      },
    ],
    footer: 'PhotoWeather © 2026 · Data via Open-Meteo API',
    lastUpdate: 'Last update',
    nextUpdate: 'Next update',
    noData: 'No data',
  }
};