    function filterAndRender(){
      syncFilterHighlights();
      const container=document.getElementById('spots-container');container.innerHTML='';if(!currentData)return;
      let filtered=categoryBaseSpots();
      if(currentSearch){
        filtered=filtered.filter(s=>{
          const haystack=[...(Object.values(s.name_i18n||{})),s.name_local,s.map_query,s.category].filter(Boolean).join(' ').toLocaleLowerCase();
          return haystack.includes(currentSearch);
        });
      }
      const rows=[];for(const spot of filtered){const metric=getMetric(spot);if(metric)rows.push({spot,metric});}rows.sort((a,b)=>{const as=Number.isFinite(Number(a.metric.score))?Number(a.metric.score):-1;const bs=Number.isFinite(Number(b.metric.score))?Number(b.metric.score):-1;return bs-as;});
      updateFilterResultSummary(rows.length);
      if(!rows.length){container.innerHTML=`<div class="empty-state">📭 ${esc(d().no_spots)}</div>`;return;}
      rows.forEach(({spot,metric})=>{
        const card=document.createElement('div');card.className='card';card.tabIndex=0;card.setAttribute('role','button');card.onclick=()=>openPlaceModal(spot,metric);card.onkeydown=e=>{if(e.target.closest('a,button,input,select,summary'))return;if(e.key==='Enter'||e.key===' '){e.preventDefault();openPlaceModal(spot,metric);}};
        const noViable=!!metric.no_viable_opportunity;const researchPending=!!metric.research_pending||!spot.opportunities?.length;const hasScore=metric.score!==null&&metric.score!==undefined&&!researchPending&&!noViable;const score=hasScore?Number(metric.score):null;const scoreClass=!hasScore?'score-low':score>=92?'score-gold':score>=80?'score-high':score>=65?'score-mid':'score-low';const flame=hasScore&&score>=92?'🔥 ':'';const scoreText=hasScore?`${flame}${score}`:'—';const scoreLabel=!hasScore?'':score>=92?d().score_excellent:score>=80?d().score_good:score>=65?d().score_fair:d().score_low_label;
        const fav=favorites.includes(spot.spot_id);const scenes=spot.scenes||[];const visibleScenes=scenes.slice(0,4);const scenePills=visibleScenes.map(x=>`<span class="scene-pill">${sceneLabel(x)}</span>`).join('');const sceneMore=scenes.length>2?`<span class="scene-pill scene-more">+${scenes.length-2}</span>`:'';
        const status=(researchPending||noViable)?'':trMessage(metric.status_key),indicator=(researchPending||noViable)?'':trMessage(metric.indicator_key),theme=metric.theme||'mountain_view',opportunityName=researchPending?d().research_pending_card:(noViable?d().no_viable_card:(metric.opportunity_name||themeLabel(theme)));const astro=(researchPending||noViable)?'':astroText(metric,theme);const darkSky=(researchPending||noViable)?'':darkSkyText(spot,theme);const navTool=navigationToolHtml(spot);const access=spot.access_note_i18n?.[currentLang]||spot.access_note_i18n?.['zh-TW'];const showIndicator=indicator&&indicator!==status;const factors=(researchPending||noViable)?[]:(metric.factors||[]);const factorHtml=factors.map(f=>`<span class="factor-pill ${f.type==='minus'?'factor-minus':'factor-plus'}">${f.type==='minus'?'−':'＋'} ${trFactor(f)}</span>`).join('');const factorMore=factors.length>2?`<span class="factor-pill factor-more">+${factors.length-2}</span>`:'';
        const reasonHtml=(researchPending||noViable)?'':`${showIndicator?`<div><span class="indicator-pill">${indicator}</span></div>`:''}${factorHtml?`<div class="factor-row card-factor-row">${factorHtml}${factorMore}</div>`:''}`;
        card.innerHTML=`<div><div class="card-header"><div class="spot-title-group"><span class="spot-name"></span><div class="spot-local-name"></div><div style="margin-top:4px"><span class="category-tag">${categoryLabel(spot.category)}</span></div></div><div class="card-header-actions"><span class="score-badge ${scoreClass}">${scoreText}${scoreLabel?`<span class="score-label">${esc(scoreLabel)}</span>`:''}</span><button class="fav-btn ${fav?'active':''}" data-fav aria-label="Favorite">★</button></div></div><div class="tags-wrapper">${scenePills}${sceneMore}</div><div class="shooting-summary"><div class="theme-winner">${(researchPending||noViable)?`📷 ${esc(opportunityName)}`:d().best_theme+esc(opportunityName)}</div>${(researchPending||noViable)?'':`<div class="best-window-row">${d().best_window}<b>${fmtWindow(metric)}</b></div>`}</div>${reasonHtml?`<div class="recommendation-reasons"><div class="recommendation-reasons-label">${esc(d().recommendation_reasons)}</div>${reasonHtml}</div>`:''}<div class="card-secondary-meta"><div class="info-row local-time-row card-meta-row">🕒 <span class="local-time-label">${d().local_time}：</span>${(spot.timezone==='Asia/Taipei'?'UTC+8':(metric.timezone_abbr||spot.timezone_abbr||spot.timezone||'—'))}</div>${(researchPending||noViable)?`<div class="info-row card-meta-row">🌡 ${formatTemp(metric.temp)}</div>`:`<div class="info-row forecast-status-row card-meta-row">${d().forecast_status}${status}<span class="desktop-forecast-meta">${metric.cloud_base_agl!=null?` | ☁️ ${d().cloud_base_label} ${metric.cloud_base_agl}m<span class="cloud-base-unit-long"> AGL</span><span class="cloud-base-unit-short"></span>`:''} | 🌡 ${formatTemp(metric.temp)}</span></div><div class="forecast-meta-row">${metric.cloud_base_agl!=null?`<span>☁️ ${d().cloud_base_label} ${metric.cloud_base_agl}m</span>`:''}<span>🌡 ${formatTemp(metric.temp)}</span></div>`}${astro?`<div class="info-row card-meta-row card-meta-astro">${astro}</div>`:''}${darkSky?`<div class="info-row card-meta-row card-meta-dark">${darkSky}</div>`:''}${access?`<div class="info-row access-note card-meta-row card-meta-access" title="${esc(access)}">⏰ ${esc(access)}</div>`:''}</div></div><div class="card-footer-tools" data-tools><div></div><div><a href="#" class="tool-link" data-weather>${d().weather_link}</a>${navTool}<a href="${radarUrl()}" target="_blank" rel="noopener noreferrer" class="tool-link">${d().radar_link}</a></div></div>`;
        card.querySelector('.spot-name').textContent=spotName(spot);const local=card.querySelector('.spot-local-name');const showLocal=!(currentRegion==='tw'&&currentLang==='zh-TW');local.textContent=showLocal&&spot.name_local&&spot.name_local!==spotName(spot)?spot.name_local:'';card.querySelector('[data-fav]').onclick=e=>toggleFavorite(spot.spot_id,e);card.querySelector('[data-tools]').onclick=e=>e.stopPropagation();card.querySelector('[data-weather]').onclick=e=>{e.preventDefault();e.stopPropagation();openWeatherModal(spot,metric);};container.appendChild(card);
      });
    }
