"""
ChaseLights — 區域與景點分類與主題標籤完整定義設定
"""

from opportunities import get_opportunities, merge_legacy_themes
from taxonomy_v004 import product_status, active_in_catalog

SCENE_TYPES = {
    "mountain", "coast", "lake", "river", "waterfall", "forest", "wetland",
    "geology", "desert", "grassland", "rural", "snow_ice", "city", "architecture",
}

THEME_TYPES = {
    "mountain_view", "sunrise", "sunset", "blue_hour", "sky_glow", "cloud_sea",
    "fog_mist", "reflection", "sunbeam", "milky_way", "long_exposure",
    "city_night", "snow_scene", "aurora",
}

# Legacy tags are retained inside REGIONS for backward compatibility. get_spots()
# converts them into the V5 two-layer model: scenes describe what is there;
# themes describe the photographic condition the weather engine predicts.
AVAILABLE_TAGS = {
    "lake", "mountain", "cloud_sea", "forest", "starlight", "coast",
    "waterfall", "aurora", "city",
}


REGIONS = {
    "tw": {
        "name_zh": "台灣",
        "name_en": "Taiwan",
        "categories": ["全部", "本島", "澎湖", "金門", "馬祖", "綠島/蘭嶼/小琉球"],
        # 格式: (lat, lon, name_zh, name_en, name_ja, name_local, category, tags)
        "spots": [
            (25.1869, 121.5208, "大屯山助航站", "Datunshan Navigation Station", "大屯山助航駅", "大屯山助航站", "本島", ["mountain", "cloud_sea", "city", "starlight"]),
            (25.02688, 121.57419, "象山六巨石攝影平台", "Xiangshan Six Boulders Viewpoint", "象山六巨石展望台", "象山六巨石", "本島", ["city", "mountain"]),
            (25.1761, 121.4103, "淡水漁人碼頭", "Tamsui Fisherman's Wharf", "淡水フィッシャーマンズワーフ", "淡水漁人碼頭", "本島", ["coast", "city"]),
            (25.1058, 121.8403, "九份不厭亭", "Jiufen Buyan Pavilion", "九份不厭亭", "九份不厭亭", "本島", ["mountain", "coast", "cloud_sea"]),
            (25.0508, 121.5050, "大稻埕碼頭", "Dadaocheng Wharf", "大稻埕埠頭", "大稻埕碼頭", "本島", ["coast", "city"]),
            (25.1270, 121.4600, "關渡大橋", "Guandu Bridge", "関渡大橋", "關渡大橋", "本島", ["coast", "city"]),
            (24.9590, 121.5340, "碧潭", "Bitan Scenic Area", "碧潭", "碧潭", "本島", ["lake", "city"]),
            (25.1410, 121.4210, "觀音山硬漢嶺", "Guanyin Mountain Yinghan Peak", "観音山硬漢嶺", "觀音山硬漢嶺", "本島", ["mountain", "cloud_sea", "city"]),
            (25.1550, 121.7830, "望幽谷", "Wangyou Valley", "望幽谷", "望幽谷", "本島", ["coast", "mountain"]),
            (25.1620, 121.7690, "和平島", "Heping Island Park", "和平島", "和平島", "本島", ["coast"]),
            (24.9850, 121.0190, "永安漁港", "Yongan Fishing Port", "永安漁港", "永安漁港", "本島", ["coast"]),
            (24.7610, 120.9090, "香山濕地", "Xiangshan Wetland", "香山湿地", "香山濕地", "本島", ["coast"]),
            (24.3630, 120.7400, "火炎山", "Huoyan Mountain", "火炎山", "火炎山", "本島", ["mountain"]),
            (24.4040, 120.8200, "雲洞山莊", "Yundong Villa", "雲洞山荘", "雲洞山莊", "本島", ["mountain", "cloud_sea"]),
            (24.3120, 120.5500, "高美濕地", "Gaomei Wetlands", "高美湿地", "高美濕地", "本島", ["coast"]),
            (24.2440, 120.9790, "鳶嘴山", "Yuanzui Mountain", "鳶嘴山", "鳶嘴山", "本島", ["mountain", "cloud_sea"]),
            (23.9670, 120.3340, "王功漁港", "Wanggong Fishing Port", "王功漁港", "王功漁港", "本島", ["coast"]),
            (23.8560, 120.9370, "日月潭", "Sun Moon Lake", "日月潭", "日月潭", "本島", ["lake", "cloud_sea", "starlight"]),
            (24.1426, 121.2712, "合歡山主峰", "Mt. Hehuan Main Peak", "合歓山主峰", "合歡山主峰", "本島", ["mountain", "cloud_sea", "starlight"]),
            (23.9120, 120.9310, "金龍山", "Jinlong Mountain", "金龍山", "金龍山", "本島", ["mountain", "cloud_sea", "starlight"]),
            (23.8930, 121.0140, "武界部落", "Wujie Tribe", "武界集落", "武界部落", "本島", ["mountain", "forest", "cloud_sea"]),
            (23.4720, 120.6830, "二延平步道", "Eryanping Trail", "二延平歩道", "二延平步道", "本島", ["mountain", "cloud_sea"]),
            (23.4750, 120.6850, "頂石棹", "Dingfazhao Trail", "頂石棹", "頂石棹", "本島", ["mountain", "forest", "cloud_sea"]),
            (23.5100, 120.8020, "阿里山", "Alishan National Scenic Area", "阿里山", "阿里山", "本島", ["mountain", "forest", "cloud_sea", "starlight"]),
            (23.0020, 120.4130, "二寮觀日亭", "Erliao Sunrise Pavilion", "二寮観日亭", "二寮觀日亭", "本島", ["mountain", "cloud_sea"]),
            (23.2820, 120.1160, "井仔腳鹽田", "Jingzijiao Tile-paved Salt Fields", "井仔脚瓦盤塩田", "井仔腳鹽田", "本島", ["coast"]),
            (22.8910, 120.3930, "田寮月世界", "Tianliao Moon World", "田寮月世界", "田寮月世界", "本島", ["mountain"]),
            (22.6200, 120.2810, "駁二藝術特區", "Pier-2 Art Center", "駁二芸術特区", "駁二藝術特區", "本島", ["city", "coast"]),
            (21.9010, 120.8530, "墾丁鵝鑾鼻", "Eluanbi Lighthouse", "鵝鑾鼻灯台", "墾丁鵝鑾鼻", "本島", ["coast", "starlight"]),
            (21.9670, 120.7240, "屏東關山", "Pingtung Guanshan Sunset", "屏東関山", "屏東關山", "本島", ["coast", "mountain"]),
            (24.8220, 121.7270, "抹茶山", "Matcha Mountain (Marian Hiking Trail)", "抹茶山", "抹茶山", "本島", ["mountain", "cloud_sea"]),
            (24.4820, 121.4930, "見晴懷古步道", "Jianqing Historic Trail", "見晴懐古歩道", "見晴懷古步道", "本島", ["forest", "mountain"]),
            (24.4420, 121.7800, "粉鳥林", "Fenniaolin Fish Harbor", "粉鳥林漁港", "粉鳥林", "本島", ["coast"]),
            (24.191966, 121.661332, "崇德清水斷崖展望點", "Chongde Qingshui Cliff Viewpoint", "崇徳清水断崖展望所", "崇德清水斷崖", "本島", ["coast", "mountain"]),
            (23.2310, 121.3250, "六十石山", "Liushidan Mountain", "六十石山", "六十石山", "本島", ["mountain", "cloud_sea", "starlight"]),
            (24.0260, 121.6320, "七星潭", "Qixingtan Beach", "七星潭", "七星潭", "本島", ["coast", "starlight"]),
            (22.4440, 120.9920, "多良車站", "Duoliang Station", "多良駅", "多良車站", "本島", ["coast"]),
            (23.1260, 121.4200, "三仙台", "Sanxiantai Bridge", "三仙台", "三仙台", "本島", ["coast", "starlight"]),
            (23.1010, 121.2210, "池上伯朗大道", "Chishang Mr. Brown Avenue", "池上ブラウンロード", "池上伯朗大道", "本島", ["mountain", "starlight"]),
            (23.470018, 120.95727, "玉山主峰", "Mt. Jade Main Peak", "玉山主峰", "玉山主峰", "本島", ["mountain", "cloud_sea", "starlight"]),
            (24.3830, 121.2330, "雪山主峰", "Mt. Xueshan Main Peak", "雪山主峰", "雪山主峰", "本島", ["mountain", "starlight"]),
            (24.4230, 121.2400, "雪山北峰", "Mt. Xueshan North Peak", "雪山北峰", "雪山北峰", "本島", ["mountain", "starlight"]),
            (24.1160, 121.3250, "奇萊主峰", "Mt. Qilai Main Peak", "奇莱主峰", "奇萊主峰", "本島", ["mountain", "cloud_sea", "starlight"]),
            (24.3620, 121.4390, "南湖大山", "Nanhu Mountain", "南湖大山", "南湖大山", "本島", ["mountain", "starlight"]),
            (23.2830, 120.9830, "嘉明湖", "Jiaming Lake", "嘉明湖", "嘉明湖", "本島", ["lake", "mountain", "starlight"]),
            (24.4610, 121.2580, "大霸尖山", "Dabajian Mountain", "大覇尖山", "大霸尖山", "本島", ["mountain", "starlight"]),
            (22.6170, 120.7500, "北大武山", "Beidawu Mountain", "北大武山", "北大武山", "本島", ["mountain", "cloud_sea", "starlight"]),
            (24.4320, 121.2860, "池有山", "Mt. Chiyou", "池有山", "池有山", "本島", ["mountain", "starlight"]),
            (24.4320, 121.3050, "桃山", "Mt. Tao", "桃山", "桃山", "本島", ["mountain", "starlight"]),
            (24.4370, 121.2640, "品田山", "Mt. Pintian", "品田山", "品田山", "本島", ["mountain", "starlight"]),
            (25.0830, 121.2930, "大古山", "Dagushan Lookout", "大古山", "大古山", "本島", ["mountain", "city"]),
            (22.8290, 120.3520, "小崗山雲臺", "Xiaogangshan Yuntai", "小崗山雲台", "小崗山雲臺", "本島", ["mountain", "city"]),
            (23.6320, 120.7920, "杉林溪", "Sun Link Sea Forest Recreation Area", "杉林渓", "杉林溪", "本島", ["forest", "waterfall", "starlight"]),
            (25.1520, 121.7680, "正濱漁港", "Zhengbin Fishing Port", "正浜漁港", "正濱漁港", "本島", ["coast", "city"]),
            (24.8320, 121.7340, "五峰旗瀑布", "Wufengqi Waterfall", "五峰旗の滝", "五峰旗瀑布", "本島", ["waterfall", "forest"]),
            (24.6757, 121.5732, "松蘿湖", "Songluo Lake", "松蘿湖", "松蘿湖", "本島", ["lake", "forest", "starlight"]),
            (24.5218, 121.4645, "加羅湖", "Jialuo Lake", "加羅湖", "加羅湖", "本島", ["lake", "mountain", "starlight"]),
            (23.6160, 119.5300, "澎湖跨海大橋", "Penghu Great Bridge", "澎湖跨海大橋", "澎湖跨海大橋", "澎湖", ["coast"]),
            (23.5810, 119.7200, "奎壁山", "Kuibishan Moses Sea Parting", "奎壁山モーゼの海割り", "奎壁山", "澎湖", ["coast", "starlight"]),
            (23.1940, 119.4340, "七美雙心石滬", "Qimei Twin-Hearts Stone Weir", "七美ダブルハート石滬", "七美雙心石滬", "澎湖", ["coast"]),
            (23.5560, 119.5620, "澎湖觀音亭", "Penghu Guanyinting", "澎湖観音亭", "澎湖觀音亭", "澎湖", ["coast", "city"]),
            (24.4490, 118.3360, "金門得月樓", "Kinmen Deyue Tower", "金門得月楼", "金門得月樓", "金門", ["city", "starlight"]),
            (24.4050, 118.3280, "翟山坑道", "Zhaishan Tunnel", "翟山坑道", "翟山坑道", "金門", ["coast"]),
            (24.4620, 118.2990, "金門慈湖", "Kinmen Cihu Lake", "金門慈湖", "金門慈湖", "金門", ["lake", "coast"]),
            (26.1580, 119.9420, "馬祖南竿", "Matsu Nangan", "馬祖南竿", "馬祖南竿", "馬祖", ["coast", "starlight"]),
            (26.3670, 120.5080, "東引燈塔", "Dongyin Lighthouse", "東引灯台", "東引燈塔", "馬祖", ["coast", "starlight"]),
            (26.2230, 119.9780, "北竿芹壁", "Beigan Qinbi Village", "北竿芹壁集落", "北竿芹壁", "馬祖", ["coast"]),
            (22.6400, 121.4910, "綠島朝日溫泉", "Green Island Zhaori Hot Spring", "緑島朝日温泉", "綠島朝日溫泉", "綠島/蘭嶼/小琉球", ["coast", "starlight"]),
            (22.0670, 121.5560, "蘭嶼東清灣", "Lanyu Dongqing Bay", "蘭嶼東清湾", "蘭嶼東清灣", "綠島/蘭嶼/小琉球", ["coast", "starlight"]),
            (22.0370, 121.5370, "蘭嶼青青草原", "Lanyu Qingqing Grassland", "蘭嶼青青草原", "蘭嶼青青草原", "綠島/蘭嶼/小琉球", ["coast", "starlight"]),
            (22.3430, 120.3800, "小琉球花瓶岩", "Liuqiu Vase Rock", "小琉球花瓶岩", "小琉球花瓶岩", "綠島/蘭嶼/小琉球", ["coast"]),
            (25.11982, 121.89314, "南雅奇岩", "Nanya Rock Formations", "南雅奇岩", "南雅奇岩", "本島", ["coast"]),
            (25.29242, 121.54446, "老梅綠石槽", "Laomei Green Reef", "老梅緑石槽", "老梅綠石槽", "本島", ["coast"]),
            (25.20886, 121.69314, "野柳地質公園", "Yehliu Geopark", "野柳地質公園", "野柳地質公園", "本島", ["coast"]),
            (24.87516, 121.84257, "外澳沙灘", "Waiao Beach", "外澳ビーチ", "外澳沙灘", "本島", ["coast"]),
            (21.92900, 120.84800, "龍磐公園", "Longpan Park", "龍磐公園", "龍磐公園", "本島", ["coast", "starlight"]),
            (23.49073, 121.51086, "石梯坪", "Shihtiping", "石梯坪", "石梯坪", "本島", ["coast"]),
            (24.426386, 118.304369, "建功嶼", "Jiangong Islet", "建功嶼", "建功嶼", "金門", ["coast"]),
            (23.60345, 119.50265, "池西岩瀑", "Chixi Columnar Basalt", "池西柱状玄武岩", "池西岩瀑", "澎湖", ["coast"]),
            (22.63366, 121.5069, "帆船鼻大草原", "Fanchuanbi Grassland", "帆船鼻大草原", "帆船鼻大草原", "綠島/蘭嶼/小琉球", ["coast", "starlight"]),
            (26.141922, 119.921072, "南竿鐵堡", "Iron Fort Nangan", "南竿鉄堡", "鐵堡", "馬祖", ["coast"]),
        ],
    },
    "jp": {
        "name_zh": "日本",
        "name_en": "Japan",
        "categories": ["全部", "北海道/東北", "關東/中部", "關西/中四國", "九州/沖繩"],
        "spots": [
            (43.6600, 142.8000, "美瑛青池", "Shirogane Blue Pond", "美瑛青い池", "白金青い池", "北海道/東北", ["lake", "forest"]),
            (43.7700, 142.3600, "旭岳", "Mt. Asahi", "旭岳", "旭岳", "北海道/東北", ["mountain", "starlight"]),
            (42.9700, 144.3700, "釧路濕原", "Kushiro Wetland", "釧路湿原", "釧路湿原", "北海道/東北", ["coast", "mountain"]),
            (41.8300, 140.1300, "函館山夜景", "Mt. Hakodate Night View", "函館山夜景", "函館山", "北海道/東北", ["city", "mountain"]),
            (43.1900, 141.0100, "小樽運河", "Otaru Canal", "小樽運河", "小樽運河", "北海道/東北", ["city", "coast"]),
            (43.0600, 144.3800, "摩周湖", "Lake Mashu", "摩周湖", "摩周湖", "北海道/東北", ["lake", "mountain"]),
            (40.8200, 140.7500, "十和田湖", "Lake Towada", "十和田湖", "十和田湖", "北海道/東北", ["lake", "forest"]),
            (38.2600, 140.8800, "松島", "Matsushima", "松島", "松島", "北海道/東北", ["coast"]),
            (38.7200, 139.8300, "磐梯山", "Mt. Bandai", "磐梯山", "磐梯山", "北海道/東北", ["mountain"]),
            (35.3600, 138.7300, "富士山 (河口湖)", "Mt. Fuji (Kawaguchiko)", "富士山 (河口湖)", "富士山", "關東/中部", ["mountain", "lake", "starlight"]),
            (35.6580, 139.7450, "東京鐵塔", "Tokyo Tower", "東京タワー", "東京タワー", "關東/中部", ["city"]),
            (35.2640, 139.1520, "鎌倉大佛", "Kamakura Great Buddha", "鎌倉大仏", "鎌倉大仏", "關東/中部", ["city"]),
            (36.1070, 138.0970, "諏訪湖", "Lake Suwa", "諏訪湖", "諏訪湖", "關東/中部", ["lake", "city"]),
            (35.6250, 139.6140, "等等力溪谷", "Todoroki Valley", "等々力渓谷", "等々力渓谷", "關東/中部", ["forest", "waterfall"]),
            (35.6700, 139.7500, "東京皇居", "Imperial Palace Tokyo", "皇居", "皇居", "關東/中部", ["city"]),
            (35.3150, 139.4950, "橫濱山下公園", "Yokohama Yamashita Park", "横浜山下公園", "山下公園", "關東/中部", ["city", "coast"]),
            (36.5600, 136.6600, "金澤兼六園", "Kanazawa Kenroku-en", "兼六園", "兼六園", "關東/中部", ["city", "lake"]),
            (35.1850, 136.9000, "名古屋城", "Nagoya Castle", "名古屋城", "名古屋城", "關東/中部", ["city"]),
            (34.7500, 137.9500, "濱名湖", "Lake Hamana", "浜名湖", "浜名湖", "關東/中部", ["lake", "coast"]),
            (35.4400, 139.6400, "橫濱港未來21", "Yokohama Minato Mirai 21", "横浜みなとみらい21", "みなとみらい", "關東/中部", ["city", "coast"]),
            (36.1600, 137.2600, "新穗高高空纜車", "Shinhotaka Ropeway", "新穂高ロープウェイ", "新穂高ロープウェイ", "關東/中部", ["mountain", "cloud_sea"]),
            (37.4500, 138.8600, "彌彥山", "Mt. Yahiko", "弥彦山", "弥彦山", "關東/中部", ["mountain"]),
            (35.0060, 135.7900, "京都清水寺", "Kiyomizu-dera Kyoto", "清水寺", "清水寺", "關西/中四國", ["city", "mountain"]),
            (34.6880, 135.5000, "大阪城公園", "Osaka Castle Park", "大阪城公園", "大阪城", "關西/中四國", ["city"]),
            (34.6550, 131.8000, "萩市城下町", "Hagi Castle Town", "萩城下町", "萩城下町", "關西/中四國", ["city"]),
            (35.4700, 133.0600, "出雲大社", "Izumo Taisha", "出雲大社", "出雲大社", "關西/中四國", ["city"]),
            (34.7760, 135.3400, "神戶六甲山", "Mt. Rokko Kobe", "六甲山", "六甲山", "關西/中四國", ["mountain", "city"]),
            (34.2600, 135.2200, "高野山", "Mt. Koya", "高野山", "高野山", "關西/中四國", ["mountain", "forest"]),
            (34.8900, 136.1000, "伊賀上野城", "Iga Ueno Castle", "伊賀上野城", "伊賀上野城", "關西/中四國", ["city"]),
            (34.0700, 134.6300, "鳴門海峽漩渦", "Naruto Whirlpools", "鳴門海峡", "鳴門海峡", "關西/中四國", ["coast"]),
            (34.6300, 133.8900, "倉敷美觀地區", "Kurashiki Bikan Historical Quarter", "倉敷美観地区", "倉敷美観地区", "關西/中四國", ["city", "lake"]),
            (33.5900, 130.5800, "福岡城跡", "Fukuoka Castle Ruins", "福岡城跡", "福岡城跡", "九州/沖繩", ["city"]),
            (33.4500, 129.9600, "唐津城", "Karatsu Castle", "唐津城", "唐津城", "九州/沖繩", ["city", "coast"]),
            (32.7500, 129.8700, "長崎哥拉巴園", "Glover Garden Nagasaki", "グラバー園", "グラバー園", "九州/沖繩", ["city", "coast"]),
            (33.5900, 130.3800, "福岡塔", "Fukuoka Tower", "福岡タワー", "福岡タワー", "九州/沖繩", ["city", "coast"]),
        ],
    },
    "us": {
        "name_zh": "美國",
        "name_en": "United States",
        "categories": ["全部", "美西", "美中", "美東", "阿拉斯加"],
        "spots": [
            (36.1070, -112.1130, "大峽谷國家公園", "Grand Canyon National Park", "グランド・キャニオン国立公園", "Grand Canyon NP", "美西", ["mountain", "starlight"]),
            (36.8790, -111.5100, "馬蹄灣", "Horseshoe Bend", "ホースシュー・ベンド", "Horseshoe Bend", "美西", ["mountain", "coast"]),
            (36.8620, -111.3740, "羚羊峽谷", "Antelope Canyon", "アンテロープ・キャニオン", "Antelope Canyon", "美西", ["mountain"]),
            (36.9830, -110.1130, "紀念碑谷", "Monument Valley", "モニュメント・バレー", "Monument Valley", "美西", ["mountain", "starlight"]),
            (38.7330, -109.5920, "拱門國家公園", "Arches National Park", "アーチズ国立公園", "Arches NP", "美西", ["mountain", "starlight"]),
            (37.5930, -112.1870, "布萊斯峽谷國家公園", "Bryce Canyon National Park", "ブライスキャニオン国立公園", "Bryce Canyon NP", "美西", ["mountain", "starlight"]),
            (37.3020, -113.0270, "錫安國家公園", "Zion National Park", "ザイオン国立公園", "Zion NP", "美西", ["mountain"]),
            (37.7310, -119.5230, "優勝美地半圓頂", "Yosemite Half Dome", "ヨセミテ ハーフドーム", "Yosemite Half Dome", "美西", ["mountain", "starlight"]),
            (37.7160, -119.6770, "優勝美地隧道觀景臺", "Yosemite Tunnel View", "ヨセミテ トンネルビュー", "Yosemite Tunnel View", "美西", ["mountain", "forest"]),
            (44.5250, -110.8380, "黃石國家公園 大稜鏡溫泉", "Yellowstone Grand Prismatic Spring", "イエローストーン グランド・プリズマティック", "Yellowstone Grand Prismatic", "美西", ["mountain", "lake"]),
            (43.7900, -110.6560, "大提頓國家公園", "Grand Teton National Park", "グランドティトン国立公園", "Grand Teton NP", "美西", ["mountain", "lake", "starlight"]),
            (46.8520, -121.7600, "雷尼爾山國家公園", "Mt. Rainier National Park", "マウント・レーニア国立公園", "Mount Rainier", "美西", ["mountain", "forest", "starlight"]),
            (42.9440, -122.1070, "火山口湖國家公園", "Crater Lake National Park", "クレーターレイク国立公園", "Crater Lake", "美西", ["lake", "mountain", "starlight"]),
            (36.4200, -116.8180, "死亡谷國家公園", "Death Valley National Park", "デスヴァレー国立公園", "Death Valley", "美西", ["mountain", "starlight"]),
            (37.8200, -122.4790, "舊金山金門大橋", "Golden Gate Bridge", "ゴールデン・ゲート・ブリッジ", "Golden Gate Bridge", "美西", ["city", "coast"]),
            (36.1150, -115.1730, "拉斯維加斯大道", "Las Vegas Strip", "ラスベガス・ストリップ", "Las Vegas Strip", "美西", ["city"]),
            (46.1910, -122.1960, "聖海倫斯火山", "Mount St. Helens", "セント・ヘレンズ山", "Mount St. Helens", "美西", ["mountain"]),
            (48.6490, -113.8000, "冰川國家公園", "Glacier National Park", "グレイシャー国立公園", "Glacier NP", "美西", ["mountain", "lake", "starlight"]),
            (47.7960, -123.6190, "奧林匹克國家公園", "Olympic National Park", "オリンピック国立公園", "Olympic NP", "美西", ["forest", "coast"]),
            (41.2920, -124.0560, "紅木國家公園", "Redwood National Park", "レッドウッド国立公園", "Redwood NP", "美西", ["forest"]),
            (38.3910, -109.8560, "峽谷地國家公園 梅薩拱門", "Canyonlands Mesa Arch", "キャニオンランズ メサアーチ", "Canyonlands Mesa Arch", "美西", ["mountain", "starlight"]),
            (33.9520, -115.9710, "約書亞樹國家公園", "Joshua Tree National Park", "ジョシュア・ツリー国立公園", "Joshua Tree NP", "美西", ["mountain", "starlight"]),
            (32.2500, -110.9420, "巨人柱國家公園", "Saguaro National Park", "サワロ国立公園", "Saguaro NP", "美西", ["mountain", "starlight"]),
            (47.6200, -122.3490, "西雅圖太空針塔", "Seattle Space Needle", "シアトル スペースニードル", "Space Needle", "美西", ["city"]),
            (34.0090, -118.4970, "聖莫尼卡碼頭", "Santa Monica Pier", "サンタモニカ・ピア", "Santa Monica Pier", "美西", ["coast", "city"]),
            (47.6080, -122.3410, "西雅圖派克市場", "Pike Place Market", "パイク・プレイス・マーケット", "Pike Place Market", "美西", ["city"]),
            (44.0680, -114.8520, "鋸齒山脈", "Sawtooth Mountains", "ソートゥース山脈", "Sawtooth Mountains", "美西", ["mountain", "starlight"]),
            (34.1610, -118.1670, "洛杉磯格里斐斯天文台", "Griffith Observatory LA", "グリフィス天文台", "Griffith Observatory", "美西", ["city", "starlight"]),
            (32.7790, -106.1710, "白沙國家公園", "White Sands National Park", "ホワイトサンズ国立公園", "White Sands", "美中", ["starlight", "mountain"]),
            (41.8830, -87.6240, "芝加哥天際線", "Chicago Skyline", "シカゴ スカイライン", "Chicago Skyline", "美中", ["city", "lake"]),
            (40.3770, -105.5210, "落磯山國家公園", "Rocky Mountain National Park", "ロッキー山脈国立公園", "Rocky Mountains", "美中", ["mountain", "starlight"]),
            (29.9580, -90.0650, "紐奧良法國區", "New Orleans French Quarter", "ニューオーリンズ フレンチ・クォーター", "French Quarter", "美中", ["city"]),
            (39.7390, -104.9920, "丹佛天際線", "Denver Skyline", "デンバー スカイライン", "Denver Skyline", "美中", ["city"]),
            (38.6250, -90.1910, "聖路易斯大拱門", "St. Louis Gateway Arch", "ゲートウェイ・アーチ", "Gateway Arch", "美中", ["city"]),
            (32.7550, -97.3310, "沃斯堡牲畜市場", "Fort Worth Stockyards", "フォートワース・ストックヤード", "Stockyards", "美中", ["city"]),
            (40.7480, -73.9860, "紐約曼哈頓天際線", "Manhattan Skyline NYC", "マンハッタン スカイライン", "Manhattan Skyline", "美東", ["city"]),
            (43.0800, -79.0710, "尼加拉瀑布", "Niagara Falls", "ナイアガラの滝", "Niagara Falls", "美東", ["waterfall", "city"]),
            (35.6110, -83.4920, "大霧山國家公園", "Great Smoky Mountains NP", "グレート・スモーキー山脈国立公園", "Great Smoky Mountains", "美東", ["mountain", "forest"]),
            (25.7930, -80.1390, "邁阿密海灘", "Miami Beach", "マイアミビーチ", "Miami Beach", "美東", ["coast", "city"]),
            (42.3600, -71.0580, "波士頓天際線", "Boston Skyline", "ボストン スカイライン", "Boston Skyline", "美東", ["city", "coast"]),
            (63.0690, -151.0080, "迪納利國家公園", "Denali National Park", "デナリ国立公園", "Denali NP", "阿拉斯加", ["mountain", "aurora", "starlight"]),
            (64.8410, -147.7180, "費爾班克斯極光", "Fairbanks Aurora", "フェアバンクス オーロラ", "Fairbanks", "阿拉斯加", ["aurora", "starlight"]),
            (65.0520, -146.0570, "珍娜溫泉", "Chena Hot Springs", "チェナ温泉", "Chena Hot Springs", "阿拉斯加", ["aurora", "starlight"]),
            (61.2180, -149.9000, "安克拉治", "Anchorage", "アンカレジ", "Anchorage", "阿拉斯加", ["city", "aurora"]),
            (60.1040, -149.4430, "蘇華德", "Seward", "スワード", "Seward", "阿拉斯加", ["coast", "aurora"]),
            (61.6400, -149.2870, "哈徹山口", "Hatcher Pass", "ハッチャーパス", "Hatcher Pass", "阿拉斯加", ["mountain", "aurora"]),
            (61.6530, -148.5970, "馬塔努斯卡冰河", "Matanuska Glacier", "マタヌスカ氷河", "Matanuska Glacier", "阿拉斯加", ["mountain", "aurora"]),
            (60.7830, -148.9070, "波蒂奇冰河", "Portage Glacier", "ポーテージ氷河", "Portage Glacier", "阿拉斯加", ["lake", "mountain"]),
            (61.1310, -146.3480, "瓦爾迪茲", "Valdez", "バルディーズ", "Valdez", "阿拉斯加", ["coast", "mountain"]),
            (58.3020, -134.4200, "朱諾", "Juneau", "ジュノー", "Juneau", "阿拉斯加", ["city", "coast"]),
            (58.4960, -134.5780, "門登霍爾冰河", "Mendenhall Glacier", "メンデンホール氷河", "Mendenhall Glacier", "阿拉斯加", ["lake", "mountain"]),
            (59.6430, -151.5380, "荷馬沙嘴", "Homer Spit", "ホーマー・スピット", "Homer Spit", "阿拉斯加", ["coast"]),
            (55.3430, -131.6470, "凱奇侃", "Ketchikan", "ケチカン", "Ketchikan", "阿拉斯加", ["coast"]),
            (59.4580, -135.3140, "史卡威", "Skagway", "スキャグウェイ", "Skagway", "阿拉斯加", ["coast", "mountain"]),
            (61.4520, -142.9690, "威朗格利-聖埃利亞斯國家公園", "Wrangell-St. Elias NP", "ランゲル・セントエライアス", "Wrangell-St. Elias", "阿拉斯加", ["mountain", "starlight"]),
            (68.1330, -149.4800, "布魯克斯山脈", "Brooks Range", "ブルックス山脈", "Brooks Range", "阿拉斯加", ["mountain", "aurora"]),
            (66.5620, -150.8130, "北極圈地標", "Arctic Circle Monument", "北極線標識", "Arctic Circle", "阿拉斯加", ["aurora", "starlight"]),
            (64.5010, -165.4060, "諾姆", "Nome", "ノーム", "Nome", "阿拉斯加", ["coast", "aurora"]),
            (58.5600, -155.1010, "卡特邁國家公園", "Katmai National Park", "カトマイ国立公園", "Katmai NP", "阿拉斯加", ["mountain", "forest"]),
            (58.4150, -135.7360, "冰河灣國家公園", "Glacier Bay National Park", "グレイシャーベイ国立公園", "Glacier Bay", "阿拉斯加", ["coast", "mountain"]),
            (57.7900, -152.4060, "柯迪亞克島", "Kodiak Island", "コディアック島", "Kodiak Island", "阿拉斯加", ["coast"]),
            (61.4070, -149.1220, "埃克盧特納湖", "Eklutna Lake", "エクルートナ湖", "Eklutna Lake", "阿拉斯加", ["lake", "aurora"]),
            (62.3230, -150.1070, "塔爾基特納", "Talkeetna", "タルキートナ", "Talkeetna", "阿拉斯加", ["mountain", "aurora"]),
            (60.9450, -149.1630, "艾利耶斯卡", "Alyeska Resort Girdwood", "アリエスカ リゾート", "Alyeska Girdwood", "阿拉斯加", ["mountain"]),
            (61.0660, -149.6500, "楚加奇州立公園", "Chugach State Park", "チュガッチ州立公園", "Chugach State Park", "阿拉斯加", ["mountain", "starlight"]),
            (66.0010, -166.6150, "白令陸橋國家保護區", "Bering Land Bridge National Preserve", "ベーリング陸橋", "Bering Land Bridge", "阿拉斯加", ["aurora"]),
            (64.7390, -156.8990, "育空河", "Yukon River", "ユーコン川", "Yukon River", "阿拉斯加", ["lake", "aurora"]),
            (68.5090, -161.0180, "諾阿塔克河", "Noatak River", "ノアタック川", "Noatak River", "阿拉斯加", ["lake", "aurora"]),
            (59.1050, -157.5500, "克拉克湖國家公園", "Lake Clark National Park", "レイククラーク国立公園", "Lake Clark", "阿拉斯加", ["lake", "aurora"]),
            (61.7890, -149.2730, "獨立礦山", "Independence Mine", "インデペンデンス鉱山", "Independence Mine", "阿拉斯加", ["mountain", "aurora"]),
        ],
    },
}

# Known summit / high-elevation camera points.  Passing the real shooting
# elevation helps Open-Meteo select/downscale to a terrain height closer to
# the photographer instead of relying only on the grid-cell DEM.
ELEVATION_OVERRIDES = {
    "合歡山主峰": 3417,
    "玉山主峰": 3952,
    "雪山主峰": 3886,
    "雪山北峰": 3703,
    "奇萊主峰": 3560,
    "南湖大山": 3742,
    "嘉明湖": 3310,
    "大霸尖山": 3492,
    "北大武山": 3092,
    "池有山": 3303,
    "桃山": 3325,
    "品田山": 3524,
    "旭岳": 2291,
    "富士山": 3776,
}

# Approximate primary shooting direction (degrees clockwise from true north).
# Only used when the composition direction is reasonably stable; omitted when
# a spot supports many directions. This allows sunrise/sunset alignment hints
# without pretending every landscape has one fixed composition.
VIEW_AZIMUTH_OVERRIDES = {
    "淡水漁人碼頭": (285, 55),
    "大稻埕碼頭": (270, 55),
    "高美濕地": (270, 60),
    "王功漁港": (270, 60),
    "井仔腳鹽田": (270, 60),
    "屏東關山": (270, 55),
    "崇德清水斷崖展望點": (155, 70),
    "七星潭": (90, 60),
    "三仙台": (90, 60),
    "龍磐公園": (90, 80),
    "石梯坪": (90, 80),
    "建功嶼": (270, 80),
    "池西岩瀑": (270, 80),
    "帆船鼻大草原": (90, 80),
    "綠島朝日溫泉": (90, 60),
    "蘭嶼東清灣": (90, 60),
    "小樽運河": (250, 80),
    "馬蹄灣": (250, 80),
    "紀念碑谷": (90, 85),
}


# Stable access constraints only. We intentionally avoid hard-coding seasonal
# business hours that may change. daylight_only means the photographic subject
# itself requires daylight; access_note_i18n warns the user to verify operator
# or facility hours separately.

# Estimated Bortle classes for astronomy-oriented locations.
# These are curated planning estimates, not live SQM measurements.  A confidence field
# is exported so the UI/score can distinguish a strong estimate from a fallback.
BORTLE_OVERRIDES = {
    '大屯山助航站': (6, 'medium'),
    '日月潭・水社壩湖景步道': (4, 'medium'),
    '日月潭': (4, 'medium'),
    '合歡山主峰': (2, 'high'),
    '金龍山': (4, 'medium'),
    '阿里山祝山觀日平台': (3, 'medium'),
    '阿里山': (3, 'medium'),
    '鵝鑾鼻燈塔': (3, 'medium'),
    '墾丁鵝鑾鼻': (3, 'medium'),
    '六十石山': (3, 'medium'),
    '龍磐公園': (3, 'medium'),
    '帆船鼻大草原': (3, 'medium'),
    '七星潭月牙灣': (5, 'medium'),
    '七星潭': (5, 'medium'),
    '三仙台': (3, 'medium'),
    '池上伯朗大道': (4, 'medium'),
    '玉山主峰': (2, 'high'),
    '雪山主峰': (2, 'high'),
    '雪山北峰': (2, 'high'),
    '奇萊主峰': (2, 'high'),
    '南湖大山': (1, 'high'),
    '嘉明湖': (2, 'high'),
    '大霸尖山': (2, 'high'),
    '北大武山': (2, 'high'),
    '池有山': (2, 'high'),
    '桃山': (2, 'high'),
    '品田山': (2, 'high'),
    '杉林溪': (4, 'medium'),
    '松蘿湖': (4, 'medium'),
    '加羅湖': (3, 'medium'),
    '奎壁山': (4, 'medium'),
    '金門得月樓': (5, 'medium'),
    '馬祖南竿': (4, 'medium'),
    '東引燈塔': (3, 'medium'),
    '綠島朝日溫泉': (3, 'medium'),
    '蘭嶼東清灣': (2, 'high'),
    '蘭嶼青青草原': (2, 'high'),
    '旭岳': (2, 'high'),
    '富士山 (河口湖)': (4, 'medium'),
    '大峽谷國家公園': (1, 'high'),
    '紀念碑谷': (2, 'high'),
    '拱門國家公園': (2, 'high'),
    '布萊斯峽谷國家公園': (2, 'high'),
    '優勝美地半圓頂': (2, 'high'),
    '大提頓國家公園': (2, 'high'),
    '雷尼爾山國家公園': (2, 'high'),
    '火山口湖國家公園': (1, 'high'),
    '死亡谷國家公園': (1, 'high'),
    '冰川國家公園': (2, 'high'),
    '峽谷地國家公園 梅薩拱門': (1, 'high'),
    '約書亞樹國家公園': (2, 'high'),
    '巨人柱國家公園': (4, 'medium'),
    '鋸齒山脈': (2, 'high'),
    '洛杉磯格里斐斯天文台': (9, 'high'),
    '白沙國家公園': (2, 'high'),
    '落磯山國家公園': (3, 'medium'),
    '迪納利國家公園': (1, 'high'),
    '費爾班克斯極光': (6, 'medium'),
    '珍娜溫泉': (3, 'medium'),
    '安克拉治': (8, 'high'),
    '蘇華德': (4, 'medium'),
    '哈徹山口': (2, 'high'),
    '馬塔努斯卡冰河': (2, 'high'),
    '威朗格利-聖埃利亞斯國家公園': (1, 'high'),
    '布魯克斯山脈': (1, 'high'),
    '北極圈地標': (1, 'high'),
    '諾姆': (4, 'medium'),
    '埃克盧特納湖': (3, 'medium'),
    '塔爾基特納': (3, 'medium'),
    '楚加奇州立公園': (3, 'medium'),
    '白令陸橋國家保護區': (1, 'high'),
    '育空河': (1, 'high'),
    '諾阿塔克河': (1, 'high'),
    '克拉克湖國家公園': (1, 'high'),
    '獨立礦山': (2, 'high')
}

def _dark_sky_meta(region_key, name_zh, category, scenes, themes):
    if not ({"milky_way", "aurora"} & set(themes or [])):
        return None
    if name_zh in BORTLE_OVERRIDES:
        cls, confidence = BORTLE_OVERRIDES[name_zh]
        source = "curated_estimate"
    else:
        # Conservative fallback for newly-added astronomy spots.  It is deliberately
        # approximate and marked low-confidence so it cannot masquerade as measured data.
        if region_key == "us" and category == "阿拉斯加":
            cls = 2 if "city" not in scenes else 7
        elif region_key == "us":
            cls = 3 if "city" not in scenes else 8
        elif region_key == "jp":
            cls = 3 if "mountain" in scenes else (8 if "city" in scenes else 5)
        else:
            if category in {"綠島/蘭嶼/小琉球", "馬祖"}:
                cls = 3
            elif "city" in scenes:
                cls = 7
            elif "mountain" in scenes:
                cls = 3
            else:
                cls = 4
        confidence = "low"
        source = "heuristic_fallback"
    cls = max(1, min(9, int(cls)))
    dark_sky_score = {1:100,2:94,3:86,4:74,5:60,6:45,7:30,8:18,9:8}[cls]
    return {
        "bortle_class": cls,
        "dark_sky_score": dark_sky_score,
        "light_pollution_source": source,
        "light_pollution_confidence": confidence,
    }

ACCESS_RULE_OVERRIDES = {
    "綠島朝日溫泉": {
        "access_mode": "opening_hours",
        "access_hours_windows": [["05:00", "10:00"], ["16:00", "23:00"]],
        "access_hours_effective_from": "2026-08-01",
        "access_hours_verified_on": "2026-09-24",
        "access_hours_source": "East Coast National Scenic Area official attraction page",
        "access_note_i18n": {
            "zh-TW": "官方 2026/08/01 起目前時段為 05:00–10:00、16:00–23:00；營運時間會隨季節調整，出發前仍應確認最新公告。",
            "en": "Current official hours from 2026-08-01 are 05:00–10:00 and 16:00–23:00; hours change seasonally, so verify the latest notice before departure.",
            "ja": "公式の現行時間（2026/08/01〜）は05:00–10:00、16:00–23:00。季節により変更されるため、出発前に最新情報を確認してください。",
        },
    },
    "南竿鐵堡": {
        "access_mode": "opening_hours_and_weather_control",
        "access_hours": ["08:00", "17:00"],
        "access_hours_source": "Matsu NSA official attraction page; verified 2026-09-24",
        "access_note_i18n": {
            "zh-TW": "官方目前列每日 08:00–17:00；長浪或強風時可能關閉。夜間不可假設可進入。",
            "en": "Official hours are currently 08:00–17:00 daily; long-period waves or strong winds may trigger closure. Do not assume night access.",
            "ja": "現在の公式営業時間は毎日08:00〜17:00。長周期波や強風時は閉鎖される場合があります。夜間入場を前提にしないでください。",
        },
    },
    "野柳地質公園": {
        "access_mode": "opening_hours",
        # Conservative all-year contract. The official site also states a
        # summer extension to 18:00, but does not define the seasonal date
        # range on the hours page; do not infer dates. A future authoritative
        # hours provider may override this 17:00 default when the active summer
        # period is explicitly known.
        "access_hours": ["08:00", "17:00"],
        "access_hours_source": "Yehliu Geopark official hours page; verified 2026-09-24",
        "access_note_i18n": {
            "zh-TW": "一般開園 08:00–17:00，夏季通常至 18:00；特殊活動可能調整，拍攝前請查官方公告",
            "en": "Normally open 08:00–17:00, usually to 18:00 in summer; verify official notices for event changes",
            "ja": "通常08:00〜17:00、夏季は通常18:00まで。イベント時は公式案内を確認してください",
        },
    },
    "羚羊峽谷": {
        "access_mode": "daylight_only",
        "access_note_i18n": {
            "zh-TW": "需參加授權導覽，實際入場時段請以營運商公告為準",
            "en": "Authorized tour required; verify current operator entry times",
            "ja": "認可ツアー参加が必要です。最新の入場時間を運営会社で確認してください",
        },
    },
    "西雅圖太空針塔": {
        "access_note_i18n": {
            "zh-TW": "觀景台有營業時間與票券限制，出發前請確認",
            "en": "Observation deck has ticketed opening hours; verify before visiting",
            "ja": "展望台は営業時間・チケット制です。訪問前に確認してください",
        },
    },
    "西雅圖派克市場": {
        "access_note_i18n": {
            "zh-TW": "市場各店營業時間不同，夜間部分區域氣氛與白天不同",
            "en": "Vendor hours vary; the market experience differs after hours",
            "ja": "店舗ごとに営業時間が異なり、夜間は雰囲気が変わります",
        },
    },
}

# V5.2: explicit photo-point / POI corrections.  Exact overrides win over
# broad legacy coordinates and name-derived scene heuristics.  map_query is
# also sent to the frontend so navigation can resolve the named POI even if
# a mountain/park covers a large area.
SPOT_OVERRIDES = {
 '南雅奇岩': {'lat': 25.11982,
          'lon': 121.89314,
          'scenes': ['coast', 'geology'],
          'themes': ['sunrise', 'sunset', 'sky_glow', 'blue_hour'],
          'map_query': '南雅奇岩地質步道 新北市瑞芳區',
          'coordinate_source': 'B28 geotagged-photo Camera Zone; official Place anchor cross-check',
          'coordinate_confidence': 'high'},
 '老梅綠石槽': {'lat': 25.29242,
           'lon': 121.54446,
           'scenes': ['coast', 'geology'],
           'themes': ['sunrise', 'sky_glow', 'blue_hour'],
           'map_query': '老梅綠石槽 新北市石門區',
           'coordinate_source': 'B28 geotagged-photo Camera Zone; official Place anchor cross-check',
           'coordinate_confidence': 'high'},
 '野柳地質公園': {'lat': 25.20886,
           'lon': 121.69314,
           'scenes': ['coast', 'geology'],
           'themes': ['mountain_view'],
           'map_query': '野柳地質公園 女王頭 新北市萬里區',
           'coordinate_source': 'B28 geotagged Queen Head Camera Zone; official park access cross-check',
           'coordinate_confidence': 'high'},
 '外澳沙灘': {'lat': 24.87516,
         'lon': 121.84257,
         'scenes': ['coast'],
         'themes': ['sunrise', 'sky_glow', 'blue_hour'],
         'map_query': '外澳沙灘 宜蘭縣頭城鎮',
         'coordinate_source': 'B28 geotagged beach Camera Zone; official Waiao/Gueishan cross-check',
         'coordinate_confidence': 'high'},
 '龍磐公園': {'lat': 21.929,
         'lon': 120.848,
         'scenes': ['coast', 'grassland', 'geology'],
         'themes': ['sunrise', 'milky_way', 'mountain_view'],
         'map_query': '龍磐公園 屏東縣恆春鎮',
         'coordinate_source': 'B28 broad Camera Zone from official Place anchor + geotagged photo evidence',
         'coordinate_confidence': 'medium'},
 '石梯坪': {'lat': 23.49073,
        'lon': 121.51086,
        'scenes': ['coast', 'geology'],
        'themes': ['sunrise', 'mountain_view'],
        'map_query': '石梯坪 花蓮縣豐濱鄉',
        'coordinate_source': 'B28 geotagged-photo Camera Zone; Tourism Administration Place anchor cross-check',
        'coordinate_confidence': 'high'},
 '建功嶼': {'lat': 24.426386,
        'lon': 118.304369,
        'scenes': ['coast', 'architecture'],
        'themes': ['sunset', 'mountain_view'],
        'map_query': '建功嶼 金門縣金城鎮',
        'coordinate_source': 'B28 geotagged tidal-causeway Camera Zone; Taiwan Tourism official Place anchor cross-check',
        'coordinate_confidence': 'high'},
 '池西岩瀑': {'lat': 23.60345,
         'lon': 119.50265,
         'scenes': ['coast', 'geology'],
         'themes': ['sunset', 'mountain_view'],
         'map_query': '池西岩瀑 澎湖縣西嶼鄉',
         'coordinate_source': 'B28 multiple geotagged-photo Camera Zone; Penghu NSA official Place anchor cross-check',
         'coordinate_confidence': 'high'},
 '帆船鼻大草原': {'lat': 22.63366,
            'lon': 121.5069,
            'scenes': ['coast', 'grassland'],
            'themes': ['sunrise', 'milky_way'],
            'map_query': '帆船鼻大草原 綠島',
            'coordinate_source': 'B28 Tourism Administration official Place anchor; broad grassland Camera Zone',
            'coordinate_confidence': 'high'},
 '南竿鐵堡': {'lat': 26.141922,
          'lon': 119.921072,
          'scenes': ['coast', 'architecture'],
          'themes': ['mountain_view'],
          'map_query': '鐵堡 南竿',
          'coordinate_source': 'B28 Wikimedia/Panoramio camera geotag; Matsu NSA official Place anchor cross-check',
          'coordinate_confidence': 'high'},
 '大屯山助航站': {'lat': 25.17614,
            'lon': 121.52244,
            'map_query': '大屯山助航站 台北',
            'coordinate_source': 'OSM/Mapcarta POI',
            'coordinate_confidence': 'medium'},
 '象山六巨石攝影平台': {'lat': 25.02688,
               'lon': 121.57419,
               'map_query': '象山六巨石 台北',
               'coordinate_source': 'curated camera point',
               'coordinate_confidence': 'high'},
 '淡水漁人碼頭': {'lat': 25.18339,
            'lon': 121.41147,
            'map_query': '淡水漁人碼頭 情人橋',
            'coordinate_source': 'Taiwan scenic POI',
            'coordinate_confidence': 'high'},
 '九份不厭亭': {'lat': 25.08923,
           'lon': 121.84752,
           'scenes': ['mountain'],
           'themes': ['mountain_view', 'sunrise', 'sunset', 'cloud_sea'],
           'map_query': '不厭亭 新北市雙溪區',
           'coordinate_source': 'New Taipei Tourism + direct photography GPS',
           'coordinate_confidence': 'high'},
 '大稻埕碼頭': {'lat': 25.0564,
           'lon': 121.50761,
           'map_query': '大稻埕碼頭 台北',
           'coordinate_source': 'curated camera point',
           'coordinate_confidence': 'high'},
 '關渡大橋': {'lat': 25.125428,
          'lon': 121.45751,
          'map_query': '關渡大橋 台北',
          'coordinate_source': 'geographic POI',
          'coordinate_confidence': 'high'},
 '碧潭': {'lat': 24.95599,
        'lon': 121.5365,
        'map_query': '碧潭風景區 新店',
        'coordinate_source': 'Taiwan tourism POI',
        'coordinate_confidence': 'high'},
 '觀音山硬漢嶺': {'lat': 25.128356,
            'lon': 121.42433,
            'map_query': '硬漢嶺 觀音山',
            'coordinate_source': 'Taiwan tourism POI',
            'coordinate_confidence': 'high'},
 '望幽谷': {'lat': 25.146003,
         'lon': 121.797514,
         'map_query': '望幽谷 基隆',
         'coordinate_source': 'curated camera point',
         'coordinate_confidence': 'high'},
 '和平島': {'lat': 25.158066,
         'lon': 121.768055,
         'map_query': '和平島地質公園',
         'coordinate_source': 'curated camera point',
         'coordinate_confidence': 'high'},
 '永安漁港': {'lat': 24.98828,
          'lon': 121.01451,
          'map_query': '永安漁港 桃園',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '香山濕地': {'lat': 24.783421,
          'lon': 120.91431,
          'scenes': ['wetland', 'coast'],
          'themes': ['sunrise', 'sunset', 'sky_glow', 'blue_hour', 'fog_mist', 'reflection'],
          'map_query': '香山濕地賞蟹步道',
          'coordinate_source': 'Taiwan tourism POI',
          'coordinate_confidence': 'high'},
 '火炎山': {'lat': 24.369396,
         'lon': 120.72806,
         'scenes': ['mountain', 'geology'],
         'themes': ['mountain_view', 'sunrise', 'sunset'],
         'map_query': '火炎山自然保留區',
         'coordinate_source': 'official natural reserve',
         'coordinate_confidence': 'high'},
 '雲洞山莊': {'lat': 24.388806,
          'lon': 120.822056,
          'map_query': '雲洞山莊 苗栗',
          'coordinate_source': 'official site DMS',
          'coordinate_confidence': 'high'},
 '高美濕地': {'lat': 24.31195,
          'lon': 120.54981,
          'scenes': ['wetland', 'coast'],
          'themes': ['sunset', 'sky_glow', 'blue_hour', 'reflection'],
          'map_query': '高美濕地木棧道',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '鳶嘴山': {'lat': 24.241111,
         'lon': 120.955028,
         'map_query': '鳶嘴山 山頂',
         'coordinate_source': 'curated summit/camera point',
         'coordinate_confidence': 'high'},
 '王功漁港': {'lat': 23.969796,
          'lon': 120.326592,
          'map_query': '王功漁港 燈塔',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '日月潭': {'lat': 23.85495,
         'lon': 120.90546,
         'scenes': ['lake', 'mountain'],
         'themes': ['sunrise', 'sunset', 'fog_mist', 'reflection', 'cloud_sea', 'milky_way'],
         'map_query': '向山眺望平台 日月潭',
         'coordinate_source': 'curated camera point (Xiangshan lookout)',
         'coordinate_confidence': 'high'},
 '合歡山主峰': {'lat': 24.1426,
           'lon': 121.2712,
           'map_query': '合歡山主峰',
           'coordinate_source': 'national park summit waypoint',
           'coordinate_confidence': 'high',
           'elevation': 3417},
 '金龍山': {'lat': 23.90023,
         'lon': 120.90869,
         'map_query': '金龍山曙光亭',
         'coordinate_source': 'curated camera point',
         'coordinate_confidence': 'high'},
 '武界部落': {'lat': 23.90874,
          'lon': 121.03959,
          'map_query': '武界部落 南投',
          'coordinate_source': 'National Cultural Memory POI',
          'coordinate_confidence': 'medium'},
 '二延平步道': {'lat': 23.422951,
           'lon': 120.651379,
           'scenes': ['mountain', 'rural'],
           'themes': ['mountain_view', 'sunrise', 'sunset', 'cloud_sea'],
           'map_query': '二延平步道 觀景平台',
           'coordinate_source': 'curated camera platform',
           'coordinate_confidence': 'high'},
 '頂石棹': {'lat': 23.474492,
         'lon': 120.701277,
         'scenes': ['mountain', 'forest', 'rural'],
         'themes': ['mountain_view', 'sunrise', 'sunset', 'cloud_sea', 'fog_mist', 'sunbeam'],
         'map_query': '頂石棹觀景臺',
         'coordinate_source': 'viewpoint coordinate',
         'coordinate_confidence': 'high'},
 '阿里山': {'lat': 23.512215,
         'lon': 120.822892,
         'scenes': ['mountain', 'forest'],
         'themes': ['mountain_view', 'sunrise', 'cloud_sea', 'milky_way'],
         'map_query': '祝山觀日平台 阿里山',
         'coordinate_source': 'Zhushan sunrise platform',
         'coordinate_confidence': 'high'},
 '二寮觀日亭': {'lat': 22.9928,
           'lon': 120.40972,
           'name_local': '二寮觀日亭',
           'scenes': ['mountain', 'rural'],
           'themes': ['sunrise', 'cloud_sea', 'mountain_view'],
           'map_query': '二寮觀日亭 台南',
           'coordinate_source': 'viewpoint POI',
           'coordinate_confidence': 'high'},
 '井仔腳鹽田': {'lat': 23.25883,
           'lon': 120.10757,
           'map_query': '井仔腳瓦盤鹽田',
           'coordinate_source': 'curated camera point',
           'coordinate_confidence': 'high'},
 '田寮月世界': {'lat': 22.886,
           'lon': 120.38898,
           'scenes': ['geology'],
           'themes': ['mountain_view', 'sunrise', 'sunset'],
           'map_query': '田寮月世界',
           'coordinate_source': 'curated geology POI',
           'coordinate_confidence': 'high'},
 '駁二藝術特區': {'lat': 22.62033,
            'lon': 120.2817,
            'scenes': ['city', 'architecture', 'coast'],
            'themes': ['blue_hour', 'city_night', 'sunset'],
            'map_query': '駁二藝術特區',
            'coordinate_source': 'POI',
            'coordinate_confidence': 'medium'},
 '墾丁鵝鑾鼻': {'lat': 21.902214,
           'lon': 120.85264,
           'map_query': '鵝鑾鼻燈塔',
           'coordinate_source': 'Taiwan Tourism lighthouse POI',
           'coordinate_confidence': 'high'},
 '屏東關山': {'lat': 21.964933,
          'lon': 120.719517,
          'map_query': '關山夕照 墾丁',
          'coordinate_source': 'curated sunset viewpoint',
          'coordinate_confidence': 'high'},
 '抹茶山': {'lat': 24.8225,
         'lon': 121.735,
         'map_query': '聖母山莊 抹茶山',
         'coordinate_source': 'best-effort camera area',
         'coordinate_confidence': 'medium'},
 '見晴懷古步道': {'lat': 24.505468,
            'lon': 121.525794,
            'map_query': '見晴懷古步道',
            'coordinate_source': 'trail POI',
            'coordinate_confidence': 'medium'},
 '粉鳥林': {'lat': 24.49792,
         'lon': 121.84276,
         'map_query': '粉鳥林漁港 宜蘭',
         'coordinate_source': 'OSM marina POI',
         'coordinate_confidence': 'high'},
 '崇德清水斷崖展望點': {'lat': 24.191966,
               'lon': 121.661332,
               'map_query': '崇德休憩據點 清水斷崖',
               'coordinate_source': 'curated camera point',
               'coordinate_confidence': 'high'},
 '六十石山': {'lat': 23.21907,
          'lon': 121.3176,
          'map_query': '六十石山 金針花',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '七星潭': {'lat': 24.031426,
         'lon': 121.62717,
         'map_query': '七星潭月牙灣',
         'coordinate_source': 'Taiwan tourism / curated camera point',
         'coordinate_confidence': 'high'},
 '多良車站': {'lat': 22.50753,
          'lon': 120.95888,
          'map_query': '多良車站',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '三仙台': {'lat': 23.12331,
         'lon': 121.40826,
         'scenes': ['coast', 'geology', 'architecture'],
         'themes': ['sunrise', 'sunset', 'sky_glow', 'blue_hour', 'long_exposure', 'milky_way'],
         'map_query': '三仙台跨海步橋',
         'coordinate_source': 'curated camera point',
         'coordinate_confidence': 'high'},
 '池上伯朗大道': {'lat': 23.09878,
            'lon': 121.2126,
            'scenes': ['rural', 'mountain'],
            'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
            'map_query': '伯朗大道 金城武樹',
            'coordinate_source': 'curated camera point',
            'coordinate_confidence': 'high'},
 '玉山主峰': {'lat': 23.470018,
          'lon': 120.95727,
          'map_query': '玉山主峰',
          'coordinate_source': 'national park summit waypoint',
          'coordinate_confidence': 'high',
          'elevation': 3952},
 '雪山主峰': {'lat': 24.383401,
          'lon': 121.231754,
          'map_query': '雪山主峰',
          'coordinate_source': 'OSM summit / baiyue data',
          'coordinate_confidence': 'high',
          'elevation': 3886},
 '雪山北峰': {'lat': 24.415,
          'lon': 121.24,
          'map_query': '雪山北峰',
          'coordinate_source': 'baiyue coordinate',
          'coordinate_confidence': 'high',
          'elevation': 3703},
 '奇萊主峰': {'lat': 24.086,
          'lon': 121.323,
          'map_query': '奇萊主峰',
          'coordinate_source': 'summit coordinate',
          'coordinate_confidence': 'high',
          'elevation': 3560},
 '南湖大山': {'lat': 24.362,
          'lon': 121.439,
          'map_query': '南湖大山',
          'coordinate_source': 'summit coordinate',
          'coordinate_confidence': 'high',
          'elevation': 3742},
 '嘉明湖': {'lat': 23.292921,
         'lon': 121.03451,
         'map_query': '嘉明湖',
         'coordinate_source': 'Taiwan landscape official',
         'coordinate_confidence': 'high',
         'elevation': 3310},
 '大霸尖山': {'lat': 24.458196,
          'lon': 121.258157,
          'map_query': '大霸尖山',
          'coordinate_source': 'Taiwan landscape official',
          'coordinate_confidence': 'high',
          'elevation': 3492},
 '北大武山': {'lat': 22.627,
          'lon': 120.752,
          'map_query': '北大武山 三角點',
          'coordinate_source': 'best-effort summit coordinate',
          'coordinate_confidence': 'medium',
          'elevation': 3092},
 '池有山': {'lat': 24.431129,
         'lon': 121.28816,
         'map_query': '池有山 三角點',
         'coordinate_source': 'Shei-Pa waypoint',
         'coordinate_confidence': 'high',
         'elevation': 3303},
 '桃山': {'lat': 24.4325,
        'lon': 121.305,
        'map_query': '桃山 三角點 武陵四秀',
        'coordinate_source': 'summit coordinate',
        'coordinate_confidence': 'high',
        'elevation': 3325},
 '品田山': {'lat': 24.4282,
         'lon': 121.2668,
         'map_query': '品田山',
         'coordinate_source': 'summit coordinate',
         'coordinate_confidence': 'high',
         'elevation': 3524},
 '大古山': {'lat': 25.10525,
         'lon': 121.290025,
         'map_query': '大古山觀景平台 桃園',
         'coordinate_source': 'viewpoint coordinate',
         'coordinate_confidence': 'high'},
 '小崗山雲臺': {'lat': 22.8229,
           'lon': 120.3497,
           'map_query': '小崗山天空迴廊',
           'coordinate_source': 'best-effort viewpoint',
           'coordinate_confidence': 'medium'},
 '杉林溪': {'lat': 23.632,
         'lon': 120.792,
         'map_query': '松瀧岩瀑布 杉林溪',
         'coordinate_source': 'existing recreation-area coordinate',
         'coordinate_confidence': 'medium'},
 '正濱漁港': {'lat': 25.152506,
          'lon': 121.768994,
          'map_query': '正濱漁港彩色屋',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '五峰旗瀑布': {'lat': 24.833,
           'lon': 121.746,
           'map_query': '五峰旗瀑布 第一層',
           'coordinate_source': 'official landscape/POI',
           'coordinate_confidence': 'high'},
 '松蘿湖': {'lat': 24.69222,
         'lon': 121.53364,
         'map_query': '松蘿湖',
         'coordinate_source': 'OSM waterbody',
         'coordinate_confidence': 'high'},
 '加羅湖': {'lat': 24.5218,
         'lon': 121.4645,
         'map_query': '加羅湖',
         'coordinate_source': 'existing; trail lake',
         'coordinate_confidence': 'medium'},
 '澎湖跨海大橋': {'lat': 23.657823,
            'lon': 119.55453,
            'map_query': '澎湖跨海大橋 西嶼端',
            'coordinate_source': 'Taiwan tourism POI',
            'coordinate_confidence': 'high'},
 '奎壁山': {'lat': 23.59968,
         'lon': 119.67137,
         'map_query': '奎壁山摩西分海',
         'coordinate_source': 'curated sunrise/tidal point',
         'coordinate_confidence': 'high'},
 '七美雙心石滬': {'lat': 23.22022,
            'lon': 119.44697,
            'map_query': '七美雙心石滬',
            'coordinate_source': 'curated camera point',
            'coordinate_confidence': 'high'},
 '澎湖觀音亭': {'lat': 23.568645,
           'lon': 119.56243,
           'map_query': '澎湖觀音亭海濱公園',
           'coordinate_source': 'Taiwan tourism POI',
           'coordinate_confidence': 'high'},
 '金門得月樓': {'lat': 24.40971,
           'lon': 118.29849,
           'map_query': '得月樓 金門',
           'coordinate_source': 'official POI',
           'coordinate_confidence': 'high'},
 '翟山坑道': {'lat': 24.390301,
          'lon': 118.32061,
          'scenes': ['architecture', 'coast'],
          'themes': ['blue_hour', 'city_night', 'long_exposure'],
          'map_query': '翟山坑道',
          'coordinate_source': 'Taiwan Tourism POI',
          'coordinate_confidence': 'high'},
 '金門慈湖': {'lat': 24.46897,
          'lon': 118.30675,
          'map_query': '慈湖 金門',
          'coordinate_source': 'curated camera point',
          'coordinate_confidence': 'high'},
 '馬祖南竿': {'lat': 26.159,
          'lon': 119.949,
          'map_query': '鐵堡 南竿 馬祖',
          'coordinate_source': 'best-effort representative camera POI',
          'coordinate_confidence': 'medium'},
 '東引燈塔': {'lat': 26.36542,
          'lon': 120.51049,
          'map_query': '東湧燈塔 馬祖',
          'coordinate_source': 'curated lighthouse',
          'coordinate_confidence': 'high'},
 '北竿芹壁': {'lat': 26.22478,
          'lon': 119.98366,
          'map_query': '芹壁聚落',
          'coordinate_source': 'curated village point',
          'coordinate_confidence': 'high'},
 '綠島朝日溫泉': {'lat': 22.63703,
            'lon': 121.50418,
            'map_query': '綠島朝日溫泉',
            'coordinate_source': 'Taiwan Tourism POI',
            'coordinate_confidence': 'high'},
 '蘭嶼東清灣': {'lat': 22.05299,
           'lon': 121.56363,
           'map_query': '東清灣 蘭嶼',
           'coordinate_source': 'Taiwan tourism open data',
           'coordinate_confidence': 'high'},
 '蘭嶼青青草原': {'lat': 22.0055,
            'lon': 121.57489,
            'scenes': ['grassland', 'coast'],
            'themes': ['sunrise', 'sunset', 'sky_glow', 'blue_hour', 'milky_way'],
            'map_query': '青青草原 蘭嶼',
            'coordinate_source': 'curated camera point',
            'coordinate_confidence': 'high'},
 '小琉球花瓶岩': {'lat': 22.355647,
            'lon': 120.380753,
            'map_query': '花瓶岩 小琉球',
            'coordinate_source': 'live camera / official area',
            'coordinate_confidence': 'high'},
 '美瑛青池': {'lat': 43.493611,
          'lon': 142.614167,
          'map_query': '白金青い池 北海道',
          'coordinate_source': 'Tokachidake Geopark official',
          'coordinate_confidence': 'high'},
 '旭岳': {'lat': 43.66358,
        'lon': 142.85397,
        'scenes': ['mountain', 'snow_ice'],
        'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way', 'snow_scene'],
        'map_query': '旭岳 山頂',
        'coordinate_source': 'summit POI',
        'coordinate_confidence': 'high'},
 '釧路濕原': {'lat': 43.07397,
          'lon': 144.32075,
          'scenes': ['wetland'],
          'themes': ['sunrise', 'sunset', 'fog_mist', 'reflection'],
          'map_query': '釧路市湿原展望台',
          'coordinate_source': 'Kushiro wetland observatory',
          'coordinate_confidence': 'high'},
 '函館山夜景': {'lat': 41.759167,
           'lon': 140.704444,
           'map_query': '函館山展望台',
           'coordinate_source': 'summit/viewpoint',
           'coordinate_confidence': 'high'},
 '小樽運河': {'lat': 43.199722,
          'lon': 141.001667,
          'scenes': ['city', 'river', 'architecture'],
          'themes': ['blue_hour', 'city_night', 'reflection', 'long_exposure'],
          'map_query': '小樽運河 浅草橋',
          'coordinate_source': 'canal POI',
          'coordinate_confidence': 'high'},
 '摩周湖': {'lat': 43.556947,
         'lon': 144.507319,
         'map_query': '摩周湖第一展望台',
         'coordinate_source': 'first observation deck',
         'coordinate_confidence': 'high'},
 '十和田湖': {'lat': 40.426538,
          'lon': 140.894325,
          'map_query': '十和田湖 休屋',
          'coordinate_source': 'Yasumiya lakeside',
          'coordinate_confidence': 'high'},
 '松島': {'lat': 38.369718,
        'lon': 141.064207,
        'scenes': ['coast', 'architecture'],
        'map_query': '松島 五大堂',
        'coordinate_source': 'Godaido exact POI',
        'coordinate_confidence': 'high'},
 '磐梯山': {'lat': 37.601111,
         'lon': 140.072222,
         'map_query': '磐梯山 山頂',
         'coordinate_source': 'JMA summit',
         'coordinate_confidence': 'high'},
 '富士山 (河口湖)': {'lat': 35.523065,
               'lon': 138.746148,
               'map_query': '大石公園 河口湖',
               'coordinate_source': 'Oishi Park lake/Fuji camera point',
               'coordinate_confidence': 'high'},
 '東京鐵塔': {'lat': 35.658656,
          'lon': 139.745364,
          'map_query': '東京タワー',
          'coordinate_source': 'Tokyo Tower POI',
          'coordinate_confidence': 'high'},
 '鎌倉大佛': {'lat': 35.316719,
          'lon': 139.535631,
          'scenes': ['architecture'],
          'themes': ['blue_hour', 'city_night'],
          'map_query': '鎌倉大仏 高徳院',
          'coordinate_source': 'Wikimedia camera / POI',
          'coordinate_confidence': 'high'},
 '諏訪湖': {'lat': 36.053326,
         'lon': 138.122711,
         'scenes': ['lake', 'city', 'mountain'],
         'themes': ['sunrise', 'sunset', 'fog_mist', 'reflection', 'city_night', 'mountain_view'],
         'map_query': '立石公園 諏訪',
         'coordinate_source': 'Tateishi Park photo point',
         'coordinate_confidence': 'high'},
 '等等力溪谷': {'lat': 35.603738,
           'lon': 139.646533,
           'scenes': ['forest', 'river', 'waterfall'],
           'themes': ['fog_mist', 'sunbeam', 'long_exposure'],
           'map_query': '等々力渓谷 不動の滝',
           'coordinate_source': 'Wikimedia camera point',
           'coordinate_confidence': 'high'},
 '東京皇居': {'lat': 35.678475,
          'lon': 139.754897,
          'scenes': ['city', 'architecture'],
          'themes': ['blue_hour', 'city_night'],
          'map_query': '皇居 二重橋',
          'coordinate_source': 'Nijubashi camera point',
          'coordinate_confidence': 'high'},
 '橫濱山下公園': {'lat': 35.446223,
            'lon': 139.655798,
            'map_query': '山下公園 横浜',
            'coordinate_source': 'MapFan POI',
            'coordinate_confidence': 'high'},
 '金澤兼六園': {'lat': 36.562138,
           'lon': 136.662506,
           'scenes': ['forest', 'lake', 'architecture'],
           'themes': ['fog_mist', 'reflection', 'sunbeam', 'blue_hour'],
           'map_query': '兼六園',
           'coordinate_source': 'MapFan/DBpedia POI',
           'coordinate_confidence': 'high'},
 '名古屋城': {'lat': 35.18475,
          'lon': 136.899688,
          'map_query': '名古屋城',
          'coordinate_source': 'historical POI dataset',
          'coordinate_confidence': 'high'},
 '濱名湖': {'lat': 34.688461,
         'lon': 137.603753,
         'scenes': ['lake', 'coast'],
         'themes': ['sunrise', 'sunset', 'sky_glow', 'blue_hour', 'reflection', 'long_exposure'],
         'map_query': '弁天島海浜公園 浜名湖',
         'coordinate_source': 'Bentenjima camera point',
         'coordinate_confidence': 'high'},
 '橫濱港未來21': {'lat': 35.4513,
             'lon': 139.6467,
             'scenes': ['city', 'coast', 'architecture'],
             'themes': ['sunset', 'blue_hour', 'city_night', 'reflection'],
             'map_query': '横浜港大さん橋 国際客船ターミナル',
             'coordinate_source': 'Osanbashi photo point',
             'coordinate_confidence': 'medium'},
 '新穗高高空纜車': {'lat': 36.267961,
             'lon': 137.601357,
             'scenes': ['mountain', 'snow_ice'],
             'themes': ['mountain_view', 'sunrise', 'sunset', 'cloud_sea', 'snow_scene'],
             'map_query': '新穂高ロープウェイ 西穂高口駅 展望台',
             'coordinate_source': 'Wikimedia camera point',
             'coordinate_confidence': 'high'},
 '彌彥山': {'lat': 37.7047,
         'lon': 138.809,
         'map_query': '弥彦山 山頂公園',
         'coordinate_source': 'summit area',
         'coordinate_confidence': 'medium'},
 '京都清水寺': {'lat': 34.994653,
           'lon': 135.784657,
           'scenes': ['architecture', 'city', 'mountain'],
           'themes': ['blue_hour', 'city_night', 'mountain_view'],
           'map_query': '清水寺 京都',
           'coordinate_source': 'historical POI dataset',
           'coordinate_confidence': 'high'},
 '大阪城公園': {'lat': 34.68734,
           'lon': 135.526,
           'scenes': ['architecture', 'city'],
           'themes': ['blue_hour', 'city_night'],
           'map_query': '大阪城天守閣',
           'coordinate_source': 'cultural-property POI',
           'coordinate_confidence': 'high'},
 '萩市城下町': {'lat': 34.410923,
           'lon': 131.393227,
           'scenes': ['architecture', 'city'],
           'themes': ['blue_hour', 'city_night'],
           'map_query': '萩城城下町 菊屋横町',
           'coordinate_source': 'Hagi castle town POI',
           'coordinate_confidence': 'high'},
 '出雲大社': {'lat': 35.402083,
          'lon': 132.685556,
          'scenes': ['architecture'],
          'themes': ['blue_hour'],
          'map_query': '出雲大社',
          'coordinate_source': 'shrine coordinate',
          'coordinate_confidence': 'high'},
 '神戶六甲山': {'lat': 34.752011,
           'lon': 135.237428,
           'map_query': '六甲山 天覧台',
           'coordinate_source': 'Tenrandai observation deck',
           'coordinate_confidence': 'high'},
 '高野山': {'lat': 34.213056,
         'lon': 135.579583,
         'scenes': ['forest', 'architecture'],
         'themes': ['fog_mist', 'sunbeam', 'blue_hour'],
         'map_query': '高野山 壇上伽藍',
         'coordinate_source': 'Wikimedia Danjo Garan camera point',
         'coordinate_confidence': 'high'},
 '伊賀上野城': {'lat': 34.7702,
           'lon': 136.127174,
           'scenes': ['architecture', 'city'],
           'themes': ['blue_hour', 'city_night'],
           'map_query': '伊賀上野城',
           'coordinate_source': 'Mie Prefecture official',
           'coordinate_confidence': 'high'},
 '鳴門海峽漩渦': {'lat': 34.24,
            'lon': 134.651,
            'scenes': ['coast', 'geology'],
            'themes': ['sunrise', 'sunset', 'long_exposure'],
            'map_query': '渦の道 鳴門',
            'coordinate_source': 'best-effort Uzu-no-Michi viewpoint',
            'coordinate_confidence': 'medium'},
 '倉敷美觀地區': {'lat': 34.595688,
            'lon': 133.771619,
            'scenes': ['city', 'architecture', 'river'],
            'themes': ['blue_hour', 'city_night', 'reflection', 'long_exposure'],
            'map_query': '倉敷美観地区 中橋',
            'coordinate_source': 'MapFan district POI',
            'coordinate_confidence': 'high'},
 '福岡城跡': {'lat': 33.5844,
          'lon': 130.3831,
          'scenes': ['architecture', 'city'],
          'themes': ['blue_hour', 'city_night'],
          'map_query': '福岡城跡 天守台',
          'coordinate_source': 'best-effort castle keep platform',
          'coordinate_confidence': 'medium'},
 '唐津城': {'lat': 33.453529,
         'lon': 129.97818,
         'scenes': ['architecture', 'city', 'coast'],
         'themes': ['sunrise', 'sunset', 'blue_hour', 'city_night'],
         'map_query': '唐津城',
         'coordinate_source': 'MapFan POI',
         'coordinate_confidence': 'high'},
 '長崎哥拉巴園': {'lat': 32.734389,
            'lon': 129.869083,
            'scenes': ['architecture', 'city', 'coast'],
            'themes': ['sunset', 'blue_hour', 'city_night'],
            'map_query': 'グラバー園 長崎',
            'coordinate_source': 'Glover Garden POI',
            'coordinate_confidence': 'high'},
 '福岡塔': {'lat': 33.593274,
         'lon': 130.351467,
         'scenes': ['architecture', 'city', 'coast'],
         'themes': ['sunset', 'blue_hour', 'city_night'],
         'map_query': '福岡タワー',
         'coordinate_source': 'MapFan POI',
         'coordinate_confidence': 'high'},
 '大峽谷國家公園': {'lat': 36.065194,
             'lon': -112.116306,
             'map_query': 'Mather Point Grand Canyon',
             'coordinate_source': 'Wikimedia camera point',
             'coordinate_confidence': 'high'},
 '馬蹄灣': {'lat': 36.879,
         'lon': -111.51,
         'map_query': 'Horseshoe Bend Overlook',
         'coordinate_source': 'existing viewpoint coordinate',
         'coordinate_confidence': 'high'},
 '羚羊峽谷': {'lat': 36.8619,
          'lon': -111.3743,
          'scenes': ['geology'],
          'themes': ['mountain_view', 'sunbeam'],
          'map_query': 'Upper Antelope Canyon',
          'coordinate_source': 'canyon POI',
          'coordinate_confidence': 'medium'},
 '紀念碑谷': {'lat': 36.982436,
          'lon': -110.112158,
          'scenes': ['geology', 'desert'],
          'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
          'map_query': 'The View Hotel Monument Valley',
          'coordinate_source': 'The View official GPS',
          'coordinate_confidence': 'high'},
 '拱門國家公園': {'lat': 38.74402,
            'lon': -109.49973,
            'scenes': ['geology', 'desert'],
            'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
            'map_query': 'Delicate Arch',
            'coordinate_source': 'NPS Delicate Arch coordinate',
            'coordinate_confidence': 'high'},
 '布萊斯峽谷國家公園': {'lat': 37.628216,
               'lon': -112.163029,
               'scenes': ['geology', 'mountain'],
               'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
               'map_query': 'Sunrise Point Bryce Canyon',
               'coordinate_source': 'USGS/Peakbagger camera point',
               'coordinate_confidence': 'high'},
 '錫安國家公園': {'lat': 37.2133,
            'lon': -112.9401,
            'scenes': ['geology', 'mountain'],
            'themes': ['mountain_view', 'sunrise', 'sunset'],
            'map_query': 'Canyon Overlook Zion National Park',
            'coordinate_source': 'Canyon Overlook camera area',
            'coordinate_confidence': 'medium'},
 '優勝美地半圓頂': {'lat': 37.730806,
             'lon': -119.573,
             'scenes': ['mountain', 'forest'],
             'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
             'map_query': 'Glacier Point Yosemite',
             'coordinate_source': 'Glacier Point / Half Dome viewpoint',
             'coordinate_confidence': 'high'},
 '優勝美地隧道觀景臺': {'lat': 37.715553,
               'lon': -119.676861,
               'map_query': 'Tunnel View Yosemite',
               'coordinate_source': 'Wikidata viewpoint',
               'coordinate_confidence': 'high'},
 '黃石國家公園 大稜鏡溫泉': {'lat': 44.523693,
                  'lon': -110.839979,
                  'scenes': ['geology', 'lake'],
                  'themes': ['mountain_view', 'fog_mist', 'reflection'],
                  'map_query': 'Grand Prismatic Spring Overlook',
                  'coordinate_source': '2026 Wikimedia camera point',
                  'coordinate_confidence': 'high'},
 '大提頓國家公園': {'lat': 43.7115,
             'lon': -110.67076,
             'scenes': ['mountain', 'river'],
             'themes': ['mountain_view', 'sunrise', 'sunset', 'reflection', 'fog_mist', 'milky_way'],
             'map_query': 'Schwabacher Landing Grand Teton',
             'coordinate_source': 'Schwabacher Landing photographer overlook',
             'coordinate_confidence': 'high'},
 '雷尼爾山國家公園': {'lat': 46.769167,
              'lon': -121.723889,
              'scenes': ['mountain', 'lake', 'forest', 'snow_ice'],
              'themes': ['mountain_view', 'sunrise', 'sunset', 'reflection', 'fog_mist', 'milky_way', 'snow_scene'],
              'map_query': 'Reflection Lakes Mount Rainier',
              'coordinate_source': 'Reflection Lakes waypoint',
              'coordinate_confidence': 'high'},
 '火山口湖國家公園': {'lat': 42.911253,
              'lon': -122.146719,
              'map_query': 'Rim Village Crater Lake',
              'coordinate_source': 'Rim Village camera point',
              'coordinate_confidence': 'high'},
 '死亡谷國家公園': {'lat': 36.42002,
             'lon': -116.8122,
             'scenes': ['desert', 'geology'],
             'themes': ['mountain_view', 'sunrise', 'sunset', 'milky_way'],
             'map_query': 'Zabriskie Point Death Valley',
             'coordinate_source': 'Zabriskie Point POI',
             'coordinate_confidence': 'high'},
 '舊金山金門大橋': {'lat': 37.82802,
             'lon': -122.48187,
             'map_query': 'Battery Spencer Golden Gate Bridge',
             'coordinate_source': 'classic bridge viewpoint',
             'coordinate_confidence': 'high'},
 '聖海倫斯火山': {'lat': 46.2753,
            'lon': -122.2174,
            'map_query': 'Johnston Ridge Observatory Mount St Helens',
            'coordinate_source': 'classic volcano viewpoint',
            'coordinate_confidence': 'medium'},
 '冰川國家公園': {'lat': 48.527,
            'lon': -113.997,
            'scenes': ['mountain', 'lake', 'forest', 'snow_ice'],
            'themes': ['mountain_view', 'sunrise', 'sunset', 'reflection', 'milky_way', 'snow_scene'],
            'map_query': 'Lake McDonald Apgar Glacier National Park',
            'coordinate_source': 'Lake McDonald camera area',
            'coordinate_confidence': 'medium'},
 '奧林匹克國家公園': {'lat': 47.710912,
              'lon': -124.415477,
              'scenes': ['coast', 'forest', 'geology'],
              'themes': ['sunset', 'sky_glow', 'blue_hour', 'long_exposure', 'fog_mist'],
              'map_query': 'Ruby Beach Olympic National Park',
              'coordinate_source': 'NGA Ruby Beach coordinate',
              'coordinate_confidence': 'high'},
 '紅木國家公園': {'lat': 41.30408,
            'lon': -124.018237,
            'scenes': ['forest'],
            'themes': ['fog_mist', 'sunbeam'],
            'map_query': 'Lady Bird Johnson Grove',
            'coordinate_source': 'NPS event location',
            'coordinate_confidence': 'high'},
 '峽谷地國家公園 梅薩拱門': {'lat': 38.388869,
                  'lon': -109.866796,
                  'scenes': ['geology', 'desert'],
                  'themes': ['sunrise', 'mountain_view', 'milky_way'],
                  'map_query': 'Mesa Arch Canyonlands',
                  'coordinate_source': 'Wikimedia sunrise camera point',
                  'coordinate_confidence': 'high'},
 '約書亞樹國家公園': {'lat': 33.926463,
              'lon': -116.187726,
              'scenes': ['desert', 'mountain'],
              'themes': ['mountain_view', 'sunset', 'milky_way'],
              'map_query': 'Keys View Joshua Tree',
              'coordinate_source': 'Wikimedia Keys View camera point',
              'coordinate_confidence': 'high'},
 '巨人柱國家公園': {'lat': 32.292297,
             'lon': -111.207879,
             'scenes': ['desert', 'mountain'],
             'themes': ['mountain_view', 'sunset', 'milky_way'],
             'map_query': 'Signal Hill Saguaro National Park',
             'coordinate_source': 'Signal Hill coordinate',
             'coordinate_confidence': 'high'},
 '鋸齒山脈': {'lat': 44.142,
          'lon': -114.923,
          'scenes': ['mountain', 'lake'],
          'themes': ['mountain_view', 'sunrise', 'sunset', 'reflection', 'milky_way'],
          'map_query': 'Redfish Lake Sawtooth',
          'coordinate_source': 'representative lake viewpoint',
          'coordinate_confidence': 'medium'},
 '芝加哥天際線': {'lat': 41.86636,
            'lon': -87.60663,
            'scenes': ['city', 'lake'],
            'themes': ['sunrise', 'sunset', 'blue_hour', 'city_night', 'reflection'],
            'map_query': 'Adler Planetarium Skyline Walk Chicago',
            'coordinate_source': 'Adler lakefront skyline camera area',
            'coordinate_confidence': 'high'},
 '落磯山國家公園': {'lat': 40.31324,
             'lon': -105.648222,
             'scenes': ['mountain', 'lake', 'forest'],
             'themes': ['mountain_view', 'sunrise', 'sunset', 'reflection', 'milky_way'],
             'map_query': 'Bear Lake Rocky Mountain National Park',
             'coordinate_source': 'Bear Lake camera point',
             'coordinate_confidence': 'high'},
 '丹佛天際線': {'lat': 39.7475,
           'lon': -104.9507,
           'map_query': 'City Park Pavilion Denver Skyline',
           'coordinate_source': 'representative skyline point',
           'coordinate_confidence': 'medium'},
 '紐約曼哈頓天際線': {'lat': 40.70438,
              'lon': -73.99059,
              'scenes': ['city', 'coast'],
              'themes': ['sunrise', 'sunset', 'blue_hour', 'city_night', 'reflection'],
              'map_query': 'Pebble Beach Brooklyn Bridge Park',
              'coordinate_source': 'Brooklyn skyline camera point',
              'coordinate_confidence': 'high'},
 '大霧山國家公園': {'lat': 35.5629,
             'lon': -83.4985,
             'map_query': 'Kuwohi Clingmans Dome',
             'coordinate_source': 'summit observation camera point',
             'coordinate_confidence': 'medium'},
 '波士頓天際線': {'lat': 42.35466,
            'lon': -71.04675,
            'map_query': 'Fan Pier Park Boston Skyline',
            'coordinate_source': 'Fan Pier camera point',
            'coordinate_confidence': 'high'},
 '馬塔努斯卡冰河': {'lat': 61.653,
             'lon': -148.597,
             'scenes': ['snow_ice', 'mountain'],
             'themes': ['mountain_view', 'snow_scene', 'aurora'],
             'map_query': 'Matanuska Glacier',
             'coordinate_source': 'existing glacier area',
             'coordinate_confidence': 'medium'},
 '塔爾基特納': {'lat': 62.323,
           'lon': -150.107,
           'scenes': ['mountain', 'rural'],
           'themes': ['mountain_view', 'sunrise', 'sunset', 'aurora'],
           'map_query': 'Talkeetna Alaska',
           'coordinate_source': 'town/Denali-view area',
           'coordinate_confidence': 'medium'},
 '育空河': {'lat': 64.739,
         'lon': -156.899,
         'scenes': ['river'],
         'themes': ['fog_mist', 'long_exposure', 'aurora'],
         'map_query': 'Yukon River Alaska',
         'coordinate_source': 'existing regional coordinate',
         'coordinate_confidence': 'low'},
 '諾阿塔克河': {'lat': 68.509,
           'lon': -161.018,
           'scenes': ['river'],
           'themes': ['fog_mist', 'long_exposure', 'aurora'],
           'map_query': 'Noatak River Alaska',
           'coordinate_source': 'existing regional coordinate',
           'coordinate_confidence': 'low'},
 '克拉克湖國家公園': {'lat': 59.105,
              'lon': -157.55,
              'scenes': ['lake', 'mountain'],
              'themes': ['mountain_view', 'reflection', 'sunrise', 'sunset', 'aurora'],
              'map_query': 'Lake Clark National Park',
              'coordinate_source': 'existing regional coordinate',
              'coordinate_confidence': 'low'}}


# Additional high-confidence US POI/viewpoint corrections added in V5.2.
SPOT_OVERRIDES.update({
    "拉斯維加斯大道": {"lat": 36.113264, "lon": -115.176372, "map_query": "Bellagio Las Vegas Strip", "coordinate_source": "Wikimedia camera/object location", "coordinate_confidence": "high"},
    "西雅圖太空針塔": {"lat": 47.620510, "lon": -122.349300, "map_query": "Space Needle Seattle", "coordinate_source": "OSM/Mapcarta POI", "coordinate_confidence": "high"},
    "聖莫尼卡碼頭": {"lat": 34.008611, "lon": -118.498611, "map_query": "Santa Monica Pier", "coordinate_source": "Wikidata POI", "coordinate_confidence": "high"},
    "西雅圖派克市場": {"lat": 47.609570, "lon": -122.342010, "map_query": "Pike Place Market Seattle", "coordinate_source": "OSM/Mapcarta POI", "coordinate_confidence": "high"},
    "洛杉磯格里斐斯天文台": {"lat": 34.118210, "lon": -118.300370, "map_query": "Griffith Observatory Los Angeles", "coordinate_source": "OSM/Mapcarta POI", "coordinate_confidence": "high"},
    "白沙國家公園": {"lat": 32.779167, "lon": -106.171944, "map_query": "White Sands National Park Visitor Center", "coordinate_source": "NPS GPS", "coordinate_confidence": "high"},
    "紐奧良法國區": {"lat": 29.958611, "lon": -90.065000, "map_query": "French Quarter New Orleans", "coordinate_source": "Wikidata/Wikipedia district center", "coordinate_confidence": "high"},
    "聖路易斯大拱門": {"lat": 38.624600, "lon": -90.185000, "map_query": "Gateway Arch St Louis", "coordinate_source": "official geographic POI", "coordinate_confidence": "high"},
    "沃斯堡牲畜市場": {"lat": 32.790261, "lon": -97.345539, "map_query": "Fort Worth Stockyards", "coordinate_source": "Texas historic district/Wikidata", "coordinate_confidence": "high"},
    "尼加拉瀑布": {"lat": 43.081528, "lon": -79.064240, "map_query": "Niagara Falls State Park Goat Island", "coordinate_source": "Niagara Falls State Park GPS", "coordinate_confidence": "high"},
    "邁阿密海灘": {"lat": 25.782950, "lon": -80.132340, "map_query": "South Beach Miami", "coordinate_source": "Apple Maps locality", "coordinate_confidence": "high"},
    "迪納利國家公園": {"lat": 63.730880, "lon": -148.917210, "map_query": "Denali Visitor Center", "coordinate_source": "OSM/Mapcarta/NPS visitor center", "coordinate_confidence": "high"},
    "珍娜溫泉": {"lat": 65.053040, "lon": -146.055600, "map_query": "Chena Hot Springs Resort", "coordinate_source": "Alaska DEC", "coordinate_confidence": "high"},
    "哈徹山口": {"lat": 61.767150, "lon": -149.322600, "map_query": "Hatcher Pass Alaska", "coordinate_source": "OSM/Mapcarta saddle", "coordinate_confidence": "high"},
    "波蒂奇冰河": {"lat": 60.784520, "lon": -148.842000, "map_query": "Begich Boggs Visitor Center Portage", "coordinate_source": "Alaska.org visitor center", "coordinate_confidence": "high"},
    "門登霍爾冰河": {"lat": 58.417180, "lon": -134.545560, "map_query": "Mendenhall Glacier Visitor Center", "coordinate_source": "OSM/Mapcarta visitor center", "coordinate_confidence": "high"},
    "北極圈地標": {"lat": 66.556010, "lon": -150.810700, "map_query": "Arctic Circle Sign Dalton Highway", "coordinate_source": "Wikimedia object location", "coordinate_confidence": "high"},
    "艾利耶斯卡": {"lat": 60.970500, "lon": -149.098000, "map_query": "Alyeska Resort Girdwood", "coordinate_source": "Wikidata resort POI", "coordinate_confidence": "high"},
    "獨立礦山": {"lat": 61.790493, "lon": -149.283392, "map_query": "Independence Mine State Historical Park", "coordinate_source": "Alaska.org park GPS", "coordinate_confidence": "high"},
})


# V5.2 location/content corrections. Coordinates are camera/navigation targets, not
# broad administrative or trailhead centroids. Taiwan corrections are based on
# the curated camera-position audit used by ChaseLights plus official/photo-point
# references where available.

# More precise display labels for broad-area entries whose navigation coordinate
# is now an actual shooting position. spot_id remains stable because the source
# tuple order is unchanged.
DISPLAY_NAME_OVERRIDES = {
    "外澳沙灘": {"zh-TW": "外澳沙灘／龜山朝日", "en": "Waiao Beach · Gueishan Sunrise", "ja": "外澳ビーチ・亀山島朝日", "local": "外澳沙灘"},
    "龍磐公園": {"zh-TW": "龍磐公園／草原海岸", "en": "Longpan Park · Grassland Coast", "ja": "龍磐公園・草原海岸", "local": "龍磐公園"},
    "石梯坪": {"zh-TW": "石梯坪海蝕平台／壺穴群", "en": "Shihtiping Marine Terraces · Potholes", "ja": "石梯坪・海食台と甌穴群", "local": "石梯坪"},
    "建功嶼": {"zh-TW": "建功嶼／退潮石板道", "en": "Jiangong Islet · Tidal Causeway", "ja": "建功嶼・干潮石畳道", "local": "建功嶼"},
    "池西岩瀑": {"zh-TW": "池西柱狀玄武岩／池西岩瀑九孔池", "en": "Chixi Columnar Basalt · Tidal Pools", "ja": "池西柱状玄武岩・九孔池", "local": "池西岩瀑"},
    "帆船鼻大草原": {"zh-TW": "帆船鼻大草原／海岬", "en": "Fanchuanbi Grassland · Headland", "ja": "帆船鼻大草原・海岬", "local": "帆船鼻大草原"},
    "南竿鐵堡": {"zh-TW": "南竿鐵堡／海防礁岩", "en": "Iron Fort · Coastal Stronghold", "ja": "南竿鉄堡・海防岩礁", "local": "鐵堡"},
    "九份不厭亭": {"zh-TW": "不厭亭", "en": "Buyan Pavilion Viewpoint", "ja": "不厭亭展望所", "local": "不厭亭"},
    "日月潭": {"zh-TW": "日月潭・水社壩湖景步道", "en": "Sun Moon Lake · Shuishe Dam Viewpoint", "ja": "日月潭・水社ダム湖畔", "local": "日月潭 水社壩"},
    "二延平步道": {"zh-TW": "二延平步道鋼構觀景平台", "en": "Eryanping Trail Viewing Platform", "ja": "二延平歩道展望台", "local": "二延平步道觀景平台"},
    "阿里山": {"zh-TW": "阿里山祝山觀日平台", "en": "Alishan Zhushan Sunrise Platform", "ja": "阿里山祝山観日平台", "local": "祝山觀日平台"},
    "七星潭": {"zh-TW": "七星潭月牙灣", "en": "Qixingtan Crescent Bay", "ja": "七星潭月牙湾", "local": "七星潭月牙灣"},
    "香山濕地": {"zh-TW": "香山濕地賞蟹步道", "en": "Xiangshan Wetland Crab Boardwalk", "ja": "香山湿地カニ観察歩道", "local": "香山濕地賞蟹步道"},
    "井仔腳鹽田": {"zh-TW": "井仔腳瓦盤鹽田", "en": "Jingzijiao Tile-paved Salt Fields", "ja": "井仔脚瓦盤塩田", "local": "井仔腳瓦盤鹽田"},
    "墾丁鵝鑾鼻": {"zh-TW": "鵝鑾鼻燈塔", "en": "Eluanbi Lighthouse", "ja": "鵝鑾鼻灯台", "local": "鵝鑾鼻燈塔"},
    "多良車站": {"zh-TW": "多良火車站觀景台", "en": "Duoliang Station Viewpoint", "ja": "多良駅展望台", "local": "多良火車站"},
}

def _derive_scenes_themes(name_zh, legacy_tags, category, region_key):
    tags = set(legacy_tags or [])
    scenes = set()
    themes = set()

    scene_map = {
        "mountain": "mountain", "coast": "coast", "lake": "lake",
        "forest": "forest", "waterfall": "waterfall", "city": "city",
    }
    for old, new in scene_map.items():
        if old in tags:
            scenes.add(new)

    text = f"{name_zh} {category}".lower()
    def has(*words):
        return any(str(w).lower() in text for w in words)

    if has("濕地", "湿原", "wetland", "marsh", "沼澤"):
        scenes.add("wetland")

    # Avoid substring false positives such as 河口湖 -> river.
    river_terms = ("運河", "溪谷", "溪", "河川", "river", "canal")
    if has(*river_terms) or name_zh.endswith(("河", "川")):
        scenes.add("river")

    if has("峽谷", "canyon", "月世界", "火炎山", "地質", "奇岩", "arches", "arch", "mesa", "monument valley"):
        scenes.add("geology")
    if has("death valley", "white sands", "沙漠", "沙丘", "desert", "dune"):
        scenes.add("desert")
    if has("冰河", "冰川", "glacier", "氷河", "雪景"):
        scenes.add("snow_ice")
    if has("草原", "青青草原", "grassland", "prairie"):
        scenes.add("grassland")
    if has("伯朗大道", "梯田", "稻田", "農場", "farm", "rice"):
        scenes.add("rural")

    # Do not classify every name containing the character 「塔」 as architecture
    # (e.g. Matanuska / Talkeetna transliterations). Use explicit architectural terms.
    architecture_terms = (
        "大橋", "橋", "鐵塔", "鉄塔", "燈塔", "灯台", "tower", "castle",
        "城", "寺", "神社", "市場", "market", "皇居", "大佛", "大仏",
        "pier", "碼頭", "埠頭", "車站", "駅", "樓", "館"
    )
    if has(*architecture_terms) or name_zh.endswith("塔"):
        scenes.add("architecture")

    if "mountain" in scenes or "geology" in scenes or "desert" in scenes or "grassland" in scenes:
        themes.update({"mountain_view", "sunrise", "sunset"})
    if "coast" in scenes:
        themes.update({"sunrise", "sunset", "sky_glow", "blue_hour"})
    if "lake" in scenes or "wetland" in scenes:
        themes.update({"sunrise", "sunset", "fog_mist", "reflection"})
    if "river" in scenes:
        themes.update({"fog_mist", "long_exposure"})
    if "forest" in scenes:
        themes.update({"fog_mist", "sunbeam"})
    if "waterfall" in scenes:
        themes.add("long_exposure")
    # Blue hour can suit architecture, but architecture alone is not evidence of
    # a city-light night scene. Only an explicit city scene may auto-enable
    # city_night; this prevents lighthouses, bridges and isolated landmarks from
    # receiving city-light hints.
    if "city" in scenes:
        themes.update({"blue_hour", "city_night"})
    elif "architecture" in scenes:
        themes.add("blue_hour")
    if "snow_ice" in scenes:
        themes.update({"snow_scene", "mountain_view"})

    if "cloud_sea" in tags:
        themes.add("cloud_sea")
    if "starlight" in tags:
        themes.add("milky_way")
    if "aurora" in tags and region_key == "us" and category == "阿拉斯加":
        themes.add("aurora")

    if not scenes:
        scenes.add("mountain")
    if not themes:
        themes.add("mountain_view")
    return sorted(scenes), sorted(themes)

def get_spots(region="tw"):
    region_key = region.lower()
    region_data = REGIONS.get(region_key, REGIONS["tw"])

    formatted_spots = []
    for idx, spot in enumerate(region_data.get("spots", []), start=1):
        if len(spot) >= 8:
            name_zh = spot[2]
            category = spot[6]
            legacy_tags = list(spot[7])
            item = {
                "spot_id": f"{region_key}-{idx:03d}",
                "lat": spot[0],
                "lon": spot[1],
                "name_i18n": {"zh-TW": name_zh, "en": spot[3], "ja": spot[4]},
                "name_local": spot[5],
                "category": category,
                "tags": legacy_tags,
            }
        else:
            name_zh = spot[2]
            category = spot[3] if len(spot) > 3 else "本島"
            legacy_tags = list(spot[4]) if len(spot) > 4 else ["mountain"]
            item = {
                "spot_id": f"{region_key}-{idx:03d}",
                "lat": spot[0], "lon": spot[1],
                "name_i18n": {"zh-TW": name_zh, "en": name_zh, "ja": name_zh},
                "name_local": name_zh, "category": category, "tags": legacy_tags,
            }

        override = SPOT_OVERRIDES.get(name_zh, {}) if region_key == "tw" else {}
        if override:
            item["lat"] = override.get("lat", item["lat"])
            item["lon"] = override.get("lon", item["lon"])
            if "tags" in override:
                legacy_tags = list(override["tags"])
                item["tags"] = legacy_tags
        display_override = DISPLAY_NAME_OVERRIDES.get(name_zh) if region_key == "tw" else None
        if display_override:
            item["name_i18n"] = {k: display_override[k] for k in ("zh-TW", "en", "ja")}
            item["name_local"] = display_override.get("local", item["name_local"])

        scenes, themes = _derive_scenes_themes(name_zh, legacy_tags, category, region_key)
        item["scenes"] = scenes
        item["themes"] = themes

        # V5.2 explicit location/scene correction layer.
        override = SPOT_OVERRIDES.get(name_zh, {})
        if "lat" in override:
            item["lat"] = float(override["lat"])
        if "lon" in override:
            item["lon"] = float(override["lon"])
        if "scenes" in override:
            item["scenes"] = list(override["scenes"])
        if "themes" in override:
            item["themes"] = list(override["themes"])
        if override.get("name_i18n_override"):
            item["name_i18n"].update(override["name_i18n_override"])
        if override.get("name_local"):
            item["name_local"] = override["name_local"]
        item["map_query"] = override.get("map_query") or item.get("name_local") or name_zh
        item["coordinate_source"] = override.get("coordinate_source", "legacy coordinate; navigation resolves named POI")
        item["coordinate_confidence"] = override.get("coordinate_confidence", "medium")
        if override.get("elevation") is not None:
            item["elevation"] = override["elevation"]

        elevation = ELEVATION_OVERRIDES.get(name_zh)
        if elevation is not None and item.get("elevation") is None:
            item["elevation"] = elevation
        view = VIEW_AZIMUTH_OVERRIDES.get(name_zh)
        if view is not None:
            item["view_azimuth"] = view[0]
            item["view_tolerance"] = view[1]
        access = ACCESS_RULE_OVERRIDES.get(name_zh)
        if access:
            item.update(access)

        # v0.04 R3 compatibility adapter: attach only manually reviewed
        # Photography Opportunities. Legacy themes remain additive so the
        # current V5.4 UI/scoring path continues to work unchanged.
        opportunities = get_opportunities(region_key, item["spot_id"])
        if opportunities:
            item["opportunities"] = opportunities
            item["themes"] = merge_legacy_themes(item.get("themes", []), opportunities)

        dark_sky = _dark_sky_meta(region_key, name_zh, category, item.get("scenes", []), item.get("themes", []))
        if dark_sky:
            item.update(dark_sky)
        item["product_status"] = product_status(item["spot_id"])
        item["active_in_catalog"] = active_in_catalog(item["spot_id"])
        formatted_spots.append(item)
    return formatted_spots
